cookbook/catalog_structure/overriding_the_mongodb_product_value.rst, cookbook/catalog_structure/overriding_the_orm_product_value.rst
Both with MySQL and MongoDB
The existing code wasn't compliant with AcmeBundle code.
master version by @mathielen : https://github.com/akeneo/pim-docs/pull/192
=> [1.4] Fixed "how to override product value"

src/Acme/Bundle/EnrichBundle/Resources/config/datagrid.yml
There's a typo in both datagrid.color.filters.updated.data_name and datagrid.color.sorters.updated.data_name
=> Fix typo in datagrid.yml

README.md, reference/import_export/connectors.rst, reference/import_export/index.rst
Adds a connector section into the import/export chapter related to the Microsoft Office supported versions for xlsx files.
=> [TR] PIM-5612: Add Excel connector supported versions

developer_guide/migration/index.rst
These two migration links are dead. I don't think anyone will need the migration notes from that old versions, so I've just removed the lines.
=> Remove dead links

conf.py
This PR fixes MathJAX URL so it uses HTTPS.
By default, the CDN URL is in http:// schema, which causes browser alerts when the site is in HTTPS.
=> Fixes MathJax CDN URL with HTTPS schema

cookbook/product_asset/add_new_transformation.rst
we mention a csv file whereas it's a yml:
- remove csv mentions and csv example
- add a yml example
=> Fix infos for asset transformation

cookbook/rule/general_information_on_rule_format.rst
Standard format has changed for metric and price attributes. Key "data" has been changed to "amount"
=> Change key data to amount in rules

cookbook/ui_customization/add_custom_information_to_a_field.rst
Min and Max labels should not show up when the value is empty
=> Updated the min/max logic

cookbook/rule/general_information_on_rule_format.rst
Standard format has changed for media attributes. 
The notion of originalFilename does not exist anymore. The value is directly the file path.
Filename is determined according to the file path.
=> Change media rule structure according to the standard format

cookbook/category/add-properties-to-category.rst, src/Acme/Bundle/EnrichBundle/Form/Type/TranslatableCategoryType.php
A typo has been fixed in the class `CategoryType` in 1.6, but not in the cookbook.
=> Fix a typo in Category override cookbook

developer_guide/installation/system_requirements/system_install_ubuntu_1604.rst
The support of MySQL 5.7 is experimental in v1.6, It's easier for everyone to copy/paste the instruction instead of searching on Google :)
=> Added command to execute to support MySQL 5.7

reference/import_export/product-import.rst
Also, fixed missing parameter `pim_connector.job_name.xlsx_product_import`
I can understand that Akeneo's code needs to be very decoupled with parameters, but from a beginner point of view, this made the example hard to understand.
Also removed duplicated block.
=> Ease the construction of Job and Validator step

reference/best_practices/index.rst
Links are not visible right now, except in the Cookbook about how to do Behat tests.
=> Add links to standards and conventions

troubleshooting/bug_qualification/index.rst
Most of the time, if you have an error in Back Office or using the REST Api, you don't have direct access to the Web debug toolbar and the profiler.
It's sad but not lost! The X-Debug-Token-Link HTTP HEADER key provide a relative link to the profiler :)
=> Added a note on X-Debug-Token-Link

cookbook/setup_data/customize_dataset.rst
Hello,
lists were not displayed correctly, in ReSt we use "-" instead of "*" in markdown.
Mickaël
=> Fixed misuse of "*" for list item

.travis.yml, README.md, conf.py
Hello,
we have very good resources to learn Akeneo on youtube, I think it could be nice to teach every technical part with "his" functional importance ("Why is this important for Julia?").
To include a Youtube video, it's really simple:
```rst
.. youtube:: https://www.youtube.com/watch?v=fmHAz9pSS38
// or
.. youtube:: fmHAz9pSS38
```
=> Introduced Youtube videos support

developer_guide/.platform.app.yaml, developer_guide/.platform/routes.yaml, developer_guide/.platform/services.yaml
Hello,
I want to allow reviewers to visit the real website, this way we don't need to do a "manual" validation on staging.
Also, if we don't need ``staging`` step we can imagine a process where when we merge the pull request, a Jenkins task deploy docs in production: what do you think?
No problem => https://github.com/mickaelandrieu/pim-docs/pull/4 then click on "Show all checks" then "Details" => WOW
Not really. We need to pay in order to use platformsh (~10€/month) and I/we need access to configure the github webhook. Then, "yes" it will works without any more action from anyone.
=> Use platformsh to deploy docs on pull requests

cookbook/rule/general_information_on_rule_format.rst
without the HH:ii:ss, the rule does not work.
=> Add HH:ii:ss for system date attributes

_themes/akeneo_rtd/layout.html, _themes/akeneo_rtd/static/css/akeneo.css, _themes/akeneo_rtd/versions.html, _themes/sphinx_rtd_theme/layout.html
A minor but useful improvement: regarding Google analytics stats, EVERY people is looking at "latest" documentation and not at the documentation for his own version.
This may lead to many errors, and probably due to the actual version position, which is not really "visible".
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> Display docs version in a better place

.travis.yml, app/config/parameters.yml, composer.json
Hello,
this is part of https://github.com/akeneo/pim-docs/issues/568.
The global idea is to make the deployment faster by remove all validation from deploy to testing workflow instead (this means we will continue to install the PIM when validating a pull request).
Today, everytime we deploy we check again the PIM application integrity embed in the docs, which was good when we didn't have travis. I'd like to let Travis handle this task too :)
> How to use/test it?
Nothing to do, only take a look at Travis build.
This contribution needs to be applied from 1.7 to master branches.
=> Added PIM app installation check on Travis

conf.py
Hello,
this is part of https://github.com/akeneo/pim-docs/issues/568.
The global idea is to not have to sed a configuration file in order to publish our documentation.
Using `PIM_VERSIONS` environment variable, we can change the versions displayed in selector of versions for each Sphinx build.
> How to use/test it?
```bash
PIM_VERSIONS=master foo bar baz 1.0
sphinx-build -b html . ./build
```
**This doesn't means you can publish a multi version docs at this moment, this is only about the versions displayed by the selector of versions.**
This contribution needs to be applied from 1.0 to master branches.
=> Introduced PIM_VERSIONS env var to set the displayable versions

styleguide/composer.json, styleguide/index.php
Hello,
this is part of https://github.com/akeneo/pim-docs/issues/568.
The global idea is to make the deployment faster by remove all validation from deploy to testing workflow instead (this means we will continue to install the PIM when validating a pull request).
Today, styleguide use the PIM dependencies, so we need to set the dependencies of styleguide in his own composer.json file.
> How to use/test it?
```bash
cd styleguide
composer install
php -S localhost:1234
```
You can see the website looks ugly (cause of css and js files that come from files that don't exists atm) but the HTML is correctly generated by Twig.
This contribution needs to be applied from 1.7 to master branches.
=> Standalone styleguide installation using composer

.platform.app.yaml
Thanks to environment variables, we can customize a little bit the build produced by platform.sh:
* remove the selector of versions
* configure the version to be the name of git branch
=> Displayed the contribution branch in built website

src/Acme/Bundle/CatalogBundle/Entity/TranslatableCategory.php
If adding a new translatable field to a category, one must override the `getTranslationFQCN` method so it returns the new `CategoryTranslation` class.
=> Fix cookbook on category translation override

.travis.yml, app/AppKernel.php
This bundle does not exists anymore on `akeneo/pim-community-dev`, on master branch, and prevent documentation deployment.
=> Remove OroRequireJSBundle from AppKernel.php

.gitignore, .travis.yml, composer.json, composer.lock, contribute_to_pim/contribution_guide.rst, contribute_to_pim/create_connector.rst, install_pim/installation_archive.rst.inc, install_pim/installation_ce_archive.rst, install_pim/system_requirements/manual_system_installation_debian9.rst, install_pim/system_requirements/system_configuration.rst.inc, install_pim/system_requirements/system_install_ubuntu_1604.rst, install_pim/system_requirements/system_requirements.rst.inc, technical_architecture/technical_information/php_ini.rst.inc
CI distribution has been changed for `trusty` (it will soon be the default environment for all Travis builds, and it is the only one implementing TLS 1.2 => needed to check the `https` links in our documentation).
As `composer update` failed, I committed the `composer.lock` file so we can simply run a `composer install` without composer complaining about it needs a GitHub token.
=> Update installation instructions for FPM usage

install_pim/system_requirements/system_requirements.rst.inc
Minimal version supporting Json Type is 5.7.8.
https://dev.mysql.com/doc/refman/5.7/en/json.html
As we use this feature, we should specify it in our system requirements.
Note: CI fixed in this PR https://github.com/akeneo/pim-docs/pull/656
=> Update minimal Mysql version supporting Json Type

technical_architecture/events/storage_events.rst
One link was a 404 in this page (resulting in a failing CI for the documentation).
Actually, I've seen that this page about events has not been updated since a lot of time, and some events were missing.
Here an update with all the events for CE +EE.
=> Update events and associated subscribers in the PIM

import_and_export_data/formats/option.rst
As I assume that `the category code` came from the "Category data structure" page, I fixed it to `option code` that is more relevant in the context.
=> Fixed `category code` to `option code`

_themes/akeneo_rtd/layout.html, _themes/akeneo_rtd/static/css/akeneo.css, _themes/akeneo_rtd/theme.conf
Hello, this fixes https://github.com/akeneo/pim-docs/issues/576.
As you know, we maintain - as of today - only versions 1.5+ of Akeneo. We should inform users they are using a deprecated version of Akeneo, motivating them to migrate: this is good for us and for the ecosystem :)
=> Introduced deprecated version warning block

import_and_export_data/guides/automate-import-exports.rst, import_and_export_data/guides/clean-csv-file-during-product-import.rst, import_and_export_data/guides/create-connector.rst, import_and_export_data/guides/product-import-from-xml-file.rst, install_pim/docker/installation_docker.rst, install_pim/manual/daemon_queue.rst, install_pim/manual/index.rst, install_pim/manual/installation_archive.rst.inc, install_pim/manual/installation_archive_ee.rst.inc, manipulate_pim_data/product_asset/mass_import.rst
The command `akeneo:batch: job` should not be used anymore in production.
It should be only used in development.
Instead, the command `akeneo:batch:job-queue-consumer-daemon` should be used.
=> Documentation to push jobs into the queue

technical_architecture/standard_format/other_entities.rst
This PR add "attribute_as_image" field for families.
Can be merged when this PR is merged on master: https://github.com/pierallard/pim-community-dev/pull/11
=> [PIM-6291] Add attribute_as_image [DO NOT MERGE NOW]

manipulate_pim_data/mass_edition/register_a_new_bulk_action.rst
This PR updates a reference in the bulk actions guide from npm to yarn and fixes an error with declaring strict types
=> Update reference from npm to yarn

developer_guide/installation/docker/installation_docker.rst
Some MongoDB elements were missing.
This fixes the GitHub issue https://github.com/akeneo/pim-community-dev/issues/7193
=> Fix incomplete Docker install instruction

install_pim/docker/installation_docker.rst, migrate_pim/index.rst, technical_architecture/best_practices/reusable_bundle.rst
The warning about increasing the `MAX_MAP_COUNT` Linux kernel setting is now useless thanks to [aaa2000](https://github.com/aaa2000) [recent contribution](https://github.com/akeneo/pim-community-dev/pull/7473).
=> Remove section about Elasticsearch requirement on Docker

install_pim/manual/system_requirements/manual_system_installation_debian9.rst, install_pim/manual/system_requirements/system_install_ubuntu_1604.rst, install_pim/manual/system_requirements/system_requirements.rst.inc
Elasticsearch 6 is now out since a few weeks. However, Akeneo **cannot** work with it for now.
Problem is, our doc is refering to the latest Elasticsearch documentation/version, meaning as of now the 6.1n which cannot work. Some users are confused on the SUG, as we only state "Elasticsearch 5.5+", meaning 6.x could work.
This PR makes it clear that only Elasticsearch 5.5 or 5.6 should be used.
=> Be clear that only Elasticsearch 5 can be used

cookbook/ui_customization/how_to_customize_menu.rst
Following what is specified in the configuration definition, I removed the unavailable options. https://github.com/akeneo/pim-community-dev/blob/1.7/src/Oro/Bundle/NavigationBundle/DependencyInjection/Configuration.php#L136
=> Remove unavailable options in the menu configuration

conf.py
It is useless as it is replaced during deployement. Only master will be kept to not have an empty string, but it would work even without it.
This way, we will never have to do this kind of PR from 1.0 till master again.
=> Remove versions from conf.py

_themes/akeneo_rtd/layout.html
This will add the same deprecate notice that is already present on 1.5 and previous documentation branches.
=> Deprecate 1.6 documentation

_themes/akeneo/layout.html, _themes/akeneo/static/css/variables-43bf553955.css
This PR adds a deprecation notice for the 2.1 branch, like we already have on 1.6 and previous.
But with the 2.0, we changed the documentation theme, so the deprecation notice had to change, too.
This change will of course NOT be merged in 2.2 for now.
=> Add a deprecation notice on 2.1

install_pim/manual/crontab_tasks.rst.inc
Many clients and partners are configuring a completeness and versioning calculations every 15mn, which has side effects like errors since several completeness calculation are run at the same time.
I've updated examples (advised the cron task to run once a day) and added a note saying that the completeness was after several tasks like import, mass action..
=> Update cron tasks CE

_themes/akeneo/layout.html, _themes/akeneo/static/css/variables-43bf553955.css
To be removed when 2.3 is officialy released.
When merged in master, the "pre-version" will be replaced by "development version" (and will never be removed from `master`).
=> Add a "pre-version" notice for 2.3

developer_guide/migration/index.rst
We had multiple tickets recently because some people don't know that they have to run composer update command to update their PIM in EE.
=> Add composer update command run for EE migration (1.7)

install_pim/docker/installation_docker.rst
The ES part of the install doc is not needed anymore because of https://github.com/akeneo/pim-community-dev/pull/8309 (same PR for enterprise and standard editions)
=> remove the ES part

install_pim/docker/installation_docker.rst
Fix docker wrong default IP. It seems that only the master is concerned, i didn't find this block of documentation in the 2.3.
=> fix docker default IP

design_pim/guides/add_a_tab_to_form.rst
The paragraph below the code contained an obvious typo `tag:` while meant `tab:`.
=> Fix a typo: tag:register -> tab:register

technical_architecture/localization/change_pim_locale.rst
- Explain where to override
- Add clear cache indication
@see https://akeneo.atlassian.net/browse/SDS-8961
| English Review and 1 GTM          | Ok
=> SDS-8961: Additional information on allowing more locales

install_pim/customize_dataset/index.rst
Fixture folder name is `src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev` (delimited with underscores).
Using of `icecat-demo-dev` leads to the installation error:
Installer data directory cannot be found.
=> Fix the fixture folder name icecat-demo-dev to icecat_demo_dev

manipulate_pim_data/product/update.rst
The service `pim_catalog.updater.product_property_setter` doesn't exist. Instead we have the `pim_catalog.updater.property_setter` service.
I could assume that this is not a typo but an idea to make the service name more consistent with:
* pim_catalog.updater.product_property_adder
* pim_catalog.updater.product_property_remover
* pim_catalog.updater.product_property_copier
but at the moment it is called without the `product_` and leads to confusion trying to follow docs.
=> Fix the property setter service name `pim_catalog.updater.property_setter`

_themes/akeneo/layout.html, _themes/akeneo/static/css/variables-43bf553955.css
While writing some documentation, I've updated a bit the style of the documentation to make it more compact and readable, nothing huge, just small tweaks:
- Line height is a bit smaller
- No more large space used for nothing
- Make deprecation notice smaller
- Fix bug of deprecation notice displaying shadow even when we didn't scroll
=> Enhance style of the documentation

import_and_export_data/formats/examples/attribute_properties.csv
Add forgotten constraints that currently exist in the PIM (in 2.3) for code's attribute.
CF https://github.com/akeneo/pim-community-dev/blob/a0f27d9673e5c58523e45c5ccde04462a755ff6f/src/Pim/Bundle/CatalogBundle/Resources/config/validation/attribute.yml#L78
=> Add constraints on code's attribute blacklist

cloud_edition/flexibility_mode/docs/pim_application.rst
The list of flexibility CRON tasks is already defined in `cloud_edition/flexibility_mode/docs/crontasks.rst`, there is no need to duplicate it.
This PR was already done on `2.0` and merged up in `2.1` and `2.2`, but not in `2.3` and `master` (probably an error during pull-up). This PR fixes the branch `2.3`, and then will be merged in `master`.
=> Remove useless cron task list

_themes/akeneo/layout.html
A deprecation notice was added but commented (so it does not appear yet) for when the 2.3 will be deprecated, but the content of the notice is wrong, and is the one of the `master` branch, saying it is a development version.
This PR updates the notice with the right message (same already present in 2.1 and 2.2).
=> Fix future deprecation notice

onboarder/installation/define_environment_variables/system_environment_variables.rst, onboarder/installation/index.rst, onboarder/prerequisites/index.rst
The SSO between the pim master and the middleware is removed in 1.2 version of the onboarder project.
This PR removes all configuration steps for the SSO.
=> AOB-375 - Remove all the bounded context PimInteraction

design_pim/guides/create_a_new_filter_type.rst
I follow the documentation in order to create [a custom filter](https://docs.akeneo.com/2.3/design_pim/guides/create_a_new_filter_type.html#declare-a-filter-provider-for-our-custom-filter).
The method getAttributeType used is annotated as deprecated :  Will be removed in 1.8. Please use getType() instead.
I don't know where is this version of Akeneo but the method getType actually exists and is not depreciated
My project is on Akeneo 2.3 but I saw that the file didn't changed since the tag 2.0.
PS :
=> Replace deprecated method by correct one

onboarder/index.rst, onboarder/installation/index.rst, onboarder/synchronization/index.rst, onboarder/troubleshooting/index.rst, technical_architecture/events/storage_events.rst, technical_architecture/events/workflow_events.rst
A customer had errors when he ran the job queue daemon command line.
According to the official PIM installation procedure this daemon is configured to be ran / supervised by supervisord process.
According to the supervisord official documentation the environment variables of the shell which runs the supervisord main process are not shared with the processes it manage. They have to be explicitly written in the `/etc/supervisor.conf` configuration file.
This PR add this information and add a troubleshooting section to ease the search of this kind of errors through the docs.akeneo.com website.
| English Review and 1 GTM          | …
=> Some supervisord configuration were missing regarding onboarder documentation

cloud_edition/flexibility_mode/docs/data_file_transfer.rst
This adds the chmod command in order to fix SFTP access when subfolders have been created by the PIM inside the SFTP transfer zone.
=> CLOUD-1050: add chmod command to fix SFTP access

_themes/akeneo/_versions.html, _themes/akeneo/static/js/versions.js, conf.py
Today, each time we release a new version, we have to redeploy the entire docs, because each version (since 1.0) have to contain links of docs from 1.0 to master.
To prevent this, and only construct the last docs branch, I propose to put a global file in the server root, like this:
```
[
{ "label": "master", "url": "/master/index.html" },
{ "label": "v3.1", "url": "/3.1/index.html" },
{ "label": "v3.0", "url": "/3.0/index.html" },
{ "label": "v2.3", "url": "/2.3/index.html" },
{ "label": "v2.2", "url": "/2.2/index.html" },
{ "label": "v2.1", "url": "/2.1/index.html" },
{ "label": "v2.0", "url": "/2.0/index.html" },
{ "label": "v1.7", "url": "/1.7/index.html" },
{ "label": "v1.6", "url": "/1.6/index.html" },
{ "label": "v1.5", "url": "/1.5/index.html" },
{ "label": "v1.4", "url": …
```
=> Fetch versions in AJAX way

manipulate_pim_data/category/add_new_properties_to_a_category.rst
We need to fix documentation because we don't use classname parameters anymore.
This PR replaces this community PR: https://github.com/akeneo/pim-community-dev/pull/10148
=> PIM-8410: Fix add new properties to a category

manipulate_pim_data/category/add_new_properties_to_a_category.rst, src/Acme/Bundle/EnrichBundle/Form/Type/CategoryType.php, src/Acme/Bundle/EnrichBundle/Form/Type/ColorType.php, src/Acme/Bundle/EnrichBundle/Form/Type/TranslatableCategoryType.php, src/Acme/Bundle/EnrichBundle/Resources/config/form_types.yml
The field type "pim_translatable_field" and the widget option don't exist anymore as a string value, but as a class name in the form type builder.
=> PIM-8410: Fix how to add new properties to a category

onboarder/installation/index.rst
Minimum version for the 3.0 pim is now the 2.2.*
=> AOB-618 update the onboarder extension version from 2.1 to 2.2

src/Acme/Bundle/NotifyConnectorBundle/Resources/config/providers.yml
In 3.1 key %pim_enrich.provider.form.job_instance.class% is not translated anywhere, in previous version it pointed to Akeneo\Platform\Bundle\ImportExportBundle\Provider\Form\JobInstanceFormProvider. Without the change following the cookbook yields 504 error.
=> Fix for not translated parameter

cloud_edition/flexibility_mode/docs/partners.rst, install_pim/manual/daemon_queue.rst, maintain_pim/scalability_guide/index.rst
On flexibility (PaaS) servers, supervisor will be replaced in favor of systemd which is native. This adds documentation on how to use the job consumer feature now.
See PR for Akeneo PIM 3.1+: https://github.com/akeneo/pim-docs/pull/1220
Changes valid for `2.0`, `2.1`, `2.2`, `2.3` and `3.0`.
=> Add instructions on how to manage job consumers on Flex (2.0 thru 3.1)

cloud_edition/flexibility_mode/docs/partners.rst
This adds instructions on how to enable disable job configurations for job consumers on Flex instances.
| Technical Review and 2 GTM        | :heavy_check_mark: 
| English Review and 1 GTM          | :heavy_check_mark: 
**Note**: Applies to 2.x and 3.x, all versions included.
=> Add instructions on how to enable/disable job configurations

_themes/akeneo/layout.html
Links of the *Guides* drop-down menu extended beyond the menu shading. The width was not large enough.  
Before:
After:
=> PIM-8907: fix width of guides drop down menu

install_pim/docker/installation_docker.rst
pim-dependencies.sh execute a composer install not a composer update
=> Fix pim-dependencies.sh description

contribute_to_pim/documentation.rst
=> Fix 3.2 documentation CI due to wrong link

conf.py
The extension `sensio.sphinx.configurationblock` has been removed recently: https://github.com/fabpot/sphinx-php/commit/990a07169de569f058492f9f6b2fca6e25bbabd5
Keep it makes the build CI fail
=> Remove unused extension sensio.sphinx.refinclude

onboarder/installation/index.rst
The Onboarder YAML configuration file was not copied in the right PIM directory
=> AOB-880: Fix copy path in Onboarder install doc

.circleci/config.yml, .gitignore, Makefile, scripts/test_php_uses.sh
The CI couldn't deploy the documentation on staging for a month. Issue were with the permissions inside the container. As the `SSH_AUTH_SOCK` is set to `1000:1000`, so we need to run rsync with the same IDs, not with CircleCI IDs which are `1001:1002`.
As I couldn't have a green CI because of the GitHub API rate limit with composer, I also fixed the use of `COMPOSER_AUTH` and added composer cache on the CI.
=> Fix deployments through CircleCI

.circleci/config.yml, Makefile
This PR removes the recent [adding of composer cache](https://github.com/akeneo/pim-docs/pull/1465) on Circle CI.
Removing the usage of `chown 1000:1000` on the SSH keys should be enough to definitively fix what the previous PR tried to fix.
=> Revert the adding of composer cache on 4.0 branch

technical_architecture/standard_format/products.rst
- Add quantified_associations in product structure documentation
- Add missing "product_models" key in product associations
- Fix consistency in array declaration ([] vs array:0 [])
=> RAC 29: add quantified associations in external API

install_pim/manual/system_requirements/system_requirements.rst.inc
If you remove the yarn.lock and executes a `yarn install` it will install the version 3.5 of JQuery. 
But the PIM is not compatible now with this version (it's not compatible with our Datagrid).
We need to specify it in our System Requirements
=> Fix JQuery version on System Requirements in 4.0

onboarder/installation/index.rst
We do not need anymore to copy/paste a YAML configuration file, as the bundle now declares its configuration all by itself.
In the process, a couple of installation steps were put as warnings, as it is critical integrators don't miss them while setting up the bundle (and one did miss them lately).
=> TIP-1412: Update documentation for PIM Onboarder bundle 4.1

contribute_to_pim/contribution_guide.rst
There is no "latest" link to access doctrine migration documentation, I update the link to target the 1.8 version which is the one used in composer dependencies.
=> fix broken link, latest doctrine migration link do not work anymore

manipulate_pim_data/rule/general_information_on_rule_format.rst
This reverts commit 0288c9a822820f4b21e5d70f80337c8e78281f03.
=> Revert "RUL-346: update completeness operators"

design_pim/guides/add_new_page.rst
The command to install assets was outdated for `4.0`
=> PIM-9384: Fix install assets command

design_pim/guides/how_to_customize_menu.rst
- Comment the ACL line by default because the menu entry won't be displayed if the ACL does not exist yet.
- Update the assets install command
=> PIM-9422: Make the menu customization doc clearer

design_pim/guides/how_to_customize_menu.rst
In this PR, i rewrote the section on addind and sub menu in the PIM.
Before:
We only explain how to add an sub menu in an existing menu (with column and navigation module already initialized) just after adding new root menu section => It's confusing.
And there is an mistake, parent of items is root menu instead of navigation module.
Now:
Separate in two section the possibility to add sub menu : 
- Adding item in an existing sub menu
- Adding item in a custom root menu menu
=> PIM-9515: fix documentation on adding sub menu in the PIM

manipulate_pim_data/category/add_new_properties_to_a_category.rst, src/Acme/Bundle/CatalogBundle/Form/Type/CategoryType.php, src/Acme/Bundle/CatalogBundle/Form/Type/TranslatableCategoryType.php, src/Acme/Bundle/CatalogBundle/Resources/config/form_types.yml
In this PR:
- The issue comes from the config override, I believe that putting the `akeneo_storage_utils` block in `config/services/prod` is wrong as it is not environment-dependent. When putting the override block in `config/services/storage_utils.yml`, the SQL dump works as intended:
The following SQL statements will be executed:
ALTER TABLE pim_catalog_category ADD description VARCHAR(255) DEFAULT NULL;
…
- adding a reminder to register the new Bundle in the app kernel config/bundles.php file.
- There is some part that reference EnrichmentBundle whereas the rest of the tutorial reference CatalogBundle => move all to CatalogBundle
- The Extension file of bundle is not AcmeAppExtension but AcmeCatalogExtension …
=> PIM-9588: Improve add new property to category doc

install_pim/docker/installation_docker.rst, install_pim/manual/installation_ce.rst, install_pim/manual/installation_ee_archive.rst
This PR fixes references to 4.0 Docker image. And do some cleanup: as we are using composer 2, no need to increase memory.
=> BH-377 Fixes ref to old Docker image and cleanup

troubleshooting/index.rst
Fix asset family identifiers stored with a different case in attributes properties
=> PIM-9735: Troubeshooting - Fix asset family identifiers command

troubleshooting/index.rst
Troubleshooting guide on how to reset & re-index Assets
See https://github.com/akeneo/pim-enterprise-dev/pull/10592
=> PIM-9775: Troubleshooting: Asset codes filtering being case sensitive

install_pim/manual/index.rst, install_pim/manual/system_requirements/system_install_ubuntu_2004.rst
Ubuntu 20.04 is the current LTS version and is more convenient to install the PIM.
I'm still keeping the 18.04 page, mainly because of the different PHP 7.4 install process. I'm open to discussion about keeping it or not.
What's different in 20.04:
- install MySQL 8.0 with APT instead of DEB package
- install PHP 7.4 without ondrej repository
- add a small paragraph about how to install Composer (well, in fact just a link to the official doc for less maintenance)
=> BH-503: Install PIM on Ubuntu 20.04

manipulate_pim_data/teamwork_assistant/calculation_step.rst
* Teamwork assistant classes were moved to `Akeneo\Pim\WorkOrganization\TeamworkAssistant` namespace in Akeneo 4 but it wasn't reflected in the documentation
* Slashes must be doubled to be properly rendered in the markdown documentation
* Slight changes in wording: "allows to log" -> "allows logging"
=> Fixed namespaces used in "Add A Calculation Step" and improved wording

Dockerfile, install_pim/docker/installation_docker.rst
The akeneo/pim-php-dev:5.0 use PHP 7.4, not compatible anymore with PIM master
=> Use correct PHP image for master install

Dockerfile, Makefile, cloud_edition/flexibility_mode/docs/disk_usage.rst, cloud_edition/flexibility_mode/docs/environments_access.rst, maintain_pim/first_aid_kit/index.rst, technical_architecture/localization/how_to_use_the_localizers.rst
During pull-up 4.0 => 5.0 we saw that build was broken due to php 8 upgrade.
It was first decided to refactor Dockerfile to move "CE dependency build" to Makefile, and use akeneo/pim-php-dev:5.0 as base image to simplify build.
But during testing, i realized that the built files were not used on the website using "wget mirror".
See https://akeneo.atlassian.net/browse/PIM-10185
for detailed analysis.
Analysis shows other unreferenced files that should be cleaned up in another pr.
=> PIM-10185: Remove styleguide unused stylesheet

reference_entities/configure_entity_limits.rst
The limit of options is hardcoded. The team decided to fix the documentation
https://akeneo.atlassian.net/browse/PIM-10202
=> PIM-10202: Fix the limit of options in a reference entity attribute

install_pim/manual/system_requirements/manual_system_installation_debian10.rst
While skimming the docs, I spotted a command line with two consecutive occurences of the php-zip package. This PR suggests a small cleaning.
=> remove duplicate zip package

Dockerfile, install_pim/docker/installation_docker.rst, maintain_pim/first_aid_kit/index.rst
Using the COMPOSER_MEMORY_LIMIT is the easiest way to increase memory for composer install/update
=> Fix install memory limit

migrate_pim/upgrade/upgrade_from_50_to_60.rst
In 5.0 the job queue was a custom queue in the database. In 6.0 the queue is handled by Symfony Messenger that can work with several adapters (database, pub/sub, ....).  
The awaiting messages need to be migrated in the new queue.
=> CPM-152: add migration command for job queue

install_pim/docker/installation_docker.rst
Update the PIM install (docker) with the new composer cache directory.
`Composer seems to have change its cache directory (its in .cache/composer, it was in .composer/cache previously. So it needs to be added as a volume too.`
Slack thread: https://akeneo.slack.com/archives/C031QDW61/p1646240778110499
=> Update the PIM install command for docker

install_pim/docker/installation_docker.rst
Composer cache directory can be different for dev macine and it should be the responsability of the dev user to mount on the correct location.
I removed the default mount. It will then not use the cache, but it's not really a big deal for such a one shot command.
As we can read [here](https://github.com/composer/composer/blob/2.2/src/Composer/Factory.php#L134), the exact location of the cache directory is really dependant of what s already present on the dev host.
=> Fix composer cache doc

migrate_pim/upgrade/upgrade_from_50_to_60.rst
Add DQI command in 5.0 to 6.0 migration, paragraph "Migrate your data"
=> PIM:10344: Add dqi command to launch in 5.0 to 6.0 migration

cloud_edition/flexibility_mode/docs/system_administration.rst, cloud_edition/flexibility_mode/index.rst
=> CLOUD-3051: Add Flexibility updates

Makefile
In case the running user (aka the dev) running `make build` is not the 1000:1000 user, we will have file permissions issues when running make build. We can avoid this by mounting the dev `/etc/password` into the container to map the correct UIDs.
It was indeed done in other commands of this Makefile and I just moved it to the base command to always use it.
=> Mount /etc/password for every Docker command

migrate_pim/upgrade/upgrade_from_40_to_50.rst, migrate_pim/upgrade/upgrade_from_50_to_60.rst
When doing a major version upgrade, the current PIM installation must be up to date with all migrations. That means *PLAYING* them all, and not just adding them as done in the Doctrine migration system.
=> Fix migrations command for major version upgrade

.circleci/config.yml, conf.py
=> Pullup 6.0 does not target 7.0 it target master directly

cloud_edition/flexibility_mode/docs/job_consumers_and_workers.rst
In Flexibility (Paas) instances, the wrapper **partners_systemctl** will be update https://github.com/akeneo/cloud-paas/pull/1256 to avoid errors raised by the command:
`$ partners_systemctl pim_job_consumer@* enable`
From now, customer won't be able to manage several daemons at once with the wrapper.
This PR removes the notes about that in this doc.
=> Flexibility: rm notes about manage several daemons at once

cloud_edition/flexibility_mode/docs/environments_access.rst, contribute_to_pim/front.rst, manipulate_pim_data/connect/configure_event_subscription_network.rst
Hey :wave:,
This PR will fix :
2 typos in `cloud_edition/flexibility_mode/docs/environments_access.rst`
1 typo in `contribute_to_pim/front.rst`
1 typo in `manipulate_pim_data/connect/configure_event_subscription_network.rst`
Best!
=> docs: fix typos

conf.py, contribute_to_pim/report_bug.rst.inc
Removed link to demo.akeneo.com as not valid anymore in conf.py and /contribute_to_pim/report_bug.rst.inc
=> SQUIR-236-6.0 Remove links to demo.akeneo.com

conf.py, contribute_to_pim/report_bug.rst.inc
Removed link to demo.akeneo.com as not valid anymore in conf.py and /contribute_to_pim/report_bug.rst.inc
=> SQUIR-236-7.0-rmv-demo remove link to demo.akeneo.com

.circleci/config.yml
Current image used is deprecated. 
`ubuntu-2204:2022.07.1` => `ubuntu-2204:current`
=> Update docker image for CI jobs

.circleci/config.yml
Current image used is deprecated.
`ubuntu-2204:2022.07.1` => `ubuntu-2204:current`
=> [Cherry-pick 7.0] Update docker image for CI jobs

migrate_pim/migrate_to_saas.rst
update the commands `pimee:database:diff` and `pimee:database:inspect` with `--env=prod`
these commands depends on the library `jfcherng/php-diff` which was required in dev environment only in PIM v6, but the library now included in prod in PIM v7 and there is no need to install it or run the commands in `--env=dev` 
=> Update inspect database commands

maintain_pim/common_issues/index.rst
This PR add a new section in the Common issue page to clarify a little issue that can happen with css instructions added into rich text editor
Related to this PIM ticket raised by a client : https://akeneo.atlassian.net/browse/PIM-11820
=> PIM : Add new section in Common issues
