akeneo/pim-docs

cookbook/product/query-products.rst
The previous one was not working, I just replaced with the right one ;)
=> Fixed query filters debug command

cookbook/catalog/manipulate-attribute.rst
Spotted this mistake while training with Remy.
=> Correctly use the attribute option manager to add the colour options

cookbook/product_asset/sftp.rst
* How to connect to an external server for asset storage
=> [TR] PIM-4719: Asset storage

README.md
Change `+++` `===` and `---` to `###` to get correct headers
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers
=> Format README headers

cookbook/catalog/common/query.rst, cookbook/catalog/product/query.rst
Replace non working "$this->container" by "$this->getContainer()"
=> Minor fix in query cookbooks

reference/import_export/product-export.rst
See https://github.com/akeneo/pim-community-dev/pull/3559
=> [TR] PIM-5127: Update the ref doc for export memory usage improvement

reference/import_export/product-export.rst
See https://github.com/akeneo/pim-community-dev/pull/3614
=> [TR] PIM-5217: Update the doc for writers rework

contributing/documentation.rst, contributing/fix_bug.rst, contributing/standards.rst, cookbook/product_asset/add_new_transformation.rst, cookbook/product_asset/how_to_connect_to_an_external_server.rst, developer_guide/migration/index.rst, reference/events/storage_events.rst, reference/technical_information/choose_database.rst
See : https://github.com/akeneo/pim-community-dev/pull/3683
=> [TR] Doc for usage of DirectToMongoDBBundle

cookbook/catalog_structure/overriding_the_orm_product_value.rst
* "model" namespace is wrong here
* wrong Baseclass for defining custom ProductValue. Leads to: No identifier/primary key specified for Entity...
=> Some mistakes with model/entity naming and wrong subclass

cookbook/category/add-properties-to-category.rst, src/Acme/Bundle/CatalogBundle/Resources/config/validation/category.yml
Fix file not found at the bottom fo this page and improve some doc.
http://docs.akeneo.com/latest/cookbook/category/add-properties-to-category.html#define-the-category-form
=> Fix file path on cookbook 'add property to category'

contributing/best_practices.rst, contributing/index.rst, cookbook/import_export/clean-csv-file-during-product-import.rst, reference/import_export/index.rst
"practice" is the noun
"to practice" is the verb
"you're practising" is the only usage of "s" instead of "c"
=> Replace practiSe by practiCe

reference/best_practices/common_best_practices.rst, reference/best_practices/index.rst, reference/best_practices/integrators.rst, reference/best_practices/reusable_bundles.rst, reference/index.rst
=> First implementation of best practices

cookbook/catalog/product/update.rst
Set scope and locale to NULL in the options
=> Fix ProductPropertySetter example

cookbook/category/add-properties-to-category.rst
Two namespaces were wrong in the doc. It was CatalogBundle instead of AppBundle. Fixed it !
=> Fix cookbook : add field to a category

reference/scalability_guide/index.rst, reference/scalability_guide/mongo_cursor_timeout_exception.rst
=> PIM-5583: Add fix to MongoCursorTimeoutException

contributing/contribution_guide.rst, contributing/index.rst
Contributor guide for Akeneo PIM project.
Inspired from Sylius guide : http://docs.sylius.org/en/latest/contributing/code/patches.html
=> [TR] Contributor guide

developer_guide/migration/index.rst
Another boring mini-link-PR... ;-)
=> Fix broken installation link

reference/index.rst, reference/product_information/index.rst
Adding product information page according to issue #267.
Product, product value, attribute, attribute types, options and product completeness tech doc.
=> Product information reference page #267

cookbook/category/add-properties-to-category.rst, src/Acme/Bundle/CatalogBundle/Entity/CategoryTranslation.php, src/Acme/Bundle/CatalogBundle/Entity/TranslatableCategory.php, src/Acme/Bundle/CatalogBundle/Resources/config/doctrine/CategoryTranslation.orm.yml, src/Acme/Bundle/CatalogBundle/Resources/config/doctrine/TranslatableCategory.orm.yml, src/Acme/Bundle/CatalogBundle/Resources/config/entities.yml, src/Acme/Bundle/EnrichBundle/Form/Type/TranslatableCategoryType.php
Add a new section to explain how to add a translatable property
=> Complete the cookbook on category override

cookbook/purge_job_execution.rst
=> PIM-5600 : Fix typo

src/Acme/Bundle/CatalogBundle/Resources/config/doctrine/Category.orm.yml, src/Acme/Bundle/CatalogBundle/Resources/config/doctrine/TranslatableCategory.orm.yml
Add missing "changeTrackingPolicy: DEFERRED_EXPLICIT" to mapping
=> Fix category override documentation

_themes/akeneo_rtd/layout.html, _themes/akeneo_rtd/static/css/akeneo.css, conf.py
=> Set search with Algolia

_themes/akeneo_rtd/versions.html, conf.py
=> Fix path on versions

developer_guide/installation/system_requirements/setup_requirements_ubuntu_1404.rst
Fix extensions installation with PHP 5.6
=> TIP-400: fix extensions to install

developer_guide/installation/index.rst, developer_guide/installation/setup_hybrid_storage_mysql_mongo.rst, developer_guide/installation/system_requirements/setup_requirements_debian8.rst, developer_guide/installation/system_requirements/setup_requirements_debian8_php7.rst, developer_guide/installation/system_requirements/setup_requirements_ubuntu_1404.rst
What's here:
* setup requirements for Debian 8
* setup requirements for Debian 8 with PHP7
* bump doctrine/mongodb-odm-bundle (see https://github.com/akeneo/pim-community-dev/pull/4741)
=> TIP-543: documentation for Akeneo 1.6 with PHP7

developer_guide/installation/setup_hybrid_storage_mysql_mongo.rst
See https://github.com/akeneo/pim-community-dev/pull/4741
=> TIP-298: bump Doctrine MongoDB ODM bundle

cookbook/notification/how_to_add_a_notification.rst, cookbook/product_asset/add_asset_default_thumbnail_for_unknown_file_types.rst, cookbook/product_asset/add_new_transformation.rst, cookbook/rule/add_custom_action_rule_engine.rst, cookbook/ui_customization/add_a_new_tab_to_an_entity_edit_form.rst
Several fixes about links.
Update doc about Notification that has been deprecated.
=> PIM-5800: Proofread and update the 1.6 technical doc

developer_guide/migration/index.rst
So far we still say that they need to contact the support to get an EE archive.
=> Update cookbook for PAPO and some typos

developer_guide/installation/system_requirements/system_requirements.rst.inc
See https://github.com/akeneo/pim-community-dev/pull/4960
=> PIM-5963: clean completeness calculation query to be SQL compliant

developer_guide/installation/installation_archive.rst
The removed lines already are in installation_archive.rst
=> [PAPO] Remove duplicate lines

cookbook/import_export/product-import-from-xml-file.rst, cookbook/ui_customization/create_a_new_filter_type.rst, reference/import_export/product-export.rst, reference/import_export/product-import.rst, src/Acme/Bundle/XmlConnectorBundle/Archiver/XmlInvalidItemWriter.php, src/Acme/Bundle/XmlConnectorBundle/DependencyInjection/AcmeXmlConnectorExtension.php, src/Acme/Bundle/XmlConnectorBundle/Job/JobParameters/SimpleXmlImport.php, src/Acme/Bundle/XmlConnectorBundle/Reader/File/XmlFileIterator.php, src/Acme/Bundle/XmlConnectorBundle/Reader/File/XmlProductReader.php, src/Acme/Bundle/XmlConnectorBundle/Resources/config/archiving.yml, src/Acme/Bundle/XmlConnectorBundle/Resources/config/job_parameters.yml, src/Acme/Bundle/XmlConnectorBundle/Resources/config/readers.yml, src/Acme/Bundle/XmlConnectorBundle/Resources/config/writers.yml, src/Acme/Bundle/XmlConnectorBundle/Resources/fixtures/products.xml, src/Acme/Bundle/XmlConnectorBundle/Resources/translations/messages.en.yml, src/Acme/Bundle/XmlConnectorBundle/Writer/XmlWriter.php
Add a section in cookbook `How to Import Products from a XML File` to explain how to support the  Invalid item export feature for Xml Connector.
=> PIM-5953: Fix and updated XmlConnectorBundle

cookbook/ui_customization/create_a_new_field_type.rst
=> Minor typo fix

cookbook/ui_customization/add_a_tab_to_product_edit_form.rst
Fix the js and html path in config
=> Fix the js and html path in config

reference/import_export/product-export.rst
Writer file path is different in v1.6 compared to v1.5
=> Writer file path difference in v1.6

cookbook/product_asset/mass_import.rst
Folder to place files & command were wrong.
=> Update the usage of the Mass Import Assets command

cookbook/product_asset/how_to_connect_to_an_external_server.rst
master version https://github.com/akeneo/pim-docs/pull/408
=> fix sftp config for assets

cookbook/product_asset/add_new_transformation.rst
Fix infos for asset transformation, replace CSV by YML.
=> Fix infos for asset transformation

developer_guide/migration/index.rst
Update infos on requesting a new archive.
=> Update infos about getting a new archive 1.5

cookbook/rule/general_information_on_rule_format.rst
replace not_empty by not empty
remove _value for copy_value and set_value.
=> Update cookbook for 1.6 rules improvements

developer_guide/migration/index.rst
Update info on how to request new archive.
=> Update infos on new archives 1.6

developer_guide/installation/setup_hybrid_storage_mysql_mongo.rst
The composer require needs to be done in last position because it needs the database connection params.
=> Fix install steps for Mongo

cookbook/import_export/create-connector.rst, src/Acme/Bundle/DummyConnectorBundle/Resources/config/form_extensions.yml, src/Acme/Bundle/DummyConnectorBundle/Resources/config/providers.yml, src/Acme/Bundle/XmlConnectorBundle/Job/JobParameters/SimpleXmlImport.php
Changes on the doc following this PR: https://github.com/akeneo/pim-community-dev/pull/5366
=> TIP-652: import export rework

developer_guide/installation/system_requirements/system_requirements.rst.inc
replace officialy by officially
=> fix typo MySQL 5.7 part

cookbook/catalog_structure/overriding_the_orm_product_value.rst
Hello,
for any Symfony developer, this task is obvious but for beginners it's not :)
I think it's better to display the command to execute after the completion of the override.
Mickaël
=> Added the command to update Doctrine schema

cookbook/catalog_structure/index.rst
=> Add a link to how_to_add_a_custom_unit_of_measure.rst

cookbook/catalog_structure/how_to_add_a_custom_unit_of_measure.rst
Depends on https://github.com/akeneo/pim-docs/pull/478 (cherry pick of cherry pick ^^)
=> Fixed extra space and minors improvements

cookbook/ui.rst, cookbook/ui_customization/how_to_customize_menu.rst
Hello,
we have no information in docs about how to create and customize the back office menu in Akeneo.
I'm not sure about the right place where to put this information, let's complete the "How to customize the UI" cookbook for now :)
Mickaël
=> Added a Menu management cookbook

cookbook/ui.rst, cookbook/ui_customization/how_to_customize_menu.rst
Cherry pick of Menu management cookbook into master
=> Cherry pick menu management

reference/product_information/index.rst
Hello,
when getting information from product model, I'm pretty sure we are beginner and not interested about customisation yet.
Also, use too much notes is counter productive and reduce the readibility of the article: what do you think ?
Mickaël
=> Removed note that doesnt bring value

developer_guide/installation/installation_archive.rst, developer_guide/installation/installation_ce_archive.rst, developer_guide/migration/index.rst
Reference 1.7 in 1.7 docs for installation and migration.
=> Updated references to 1.7 in 1.7 docs

cookbook/catalog_structure/creating_a_reference_data.rst, cookbook/ui.rst, cookbook/ui_customization/create_a_reference_data_crud.rst
Hello, this is part of the cookbooks/tutorial to help a beginner create a reference data and be able to manage it in the back office. (see https://github.com/akeneo/pim-docs/issues/488)
Note this pull request depends on https://github.com/akeneo/pim-docs/pull/487 as we need to install CustomEntity Bundle and understand what it provides.
> Needed to be cherry picked in ``1.6``, ``1.7`` and ``master`` branches.
=> Updated the CRUD of reference data from v1.3

reference/best_practices/core/behat.rst
=> Fix selenium version typo

cookbook/ui_customization/add_a_custom_button_to_product_edit_form.rst
Small fix, for avoiding scripts loading to return 404.
=> fix filepath for resources causing 404 when loading js

cookbook/rule/general_information_on_rule_format.rst
It's not supported, need to remove it.
=> Remove "add" for collection

_themes/akeneo_rtd/static/css/akeneo.css, reference/import_export/formats/attribute.rst, reference/import_export/formats/examples/attribute.csv, reference/import_export/formats/examples/attribute_properties.csv, reference/import_export/formats/examples/attribute_type.csv, reference/product_information/index.rst
The new table is rendered as follows:
=> Add more info on attribute validation & default values

_themes/akeneo_rtd/layout.html
=> Add GA tracker

cookbook/catalog_structure/creating_a_reference_data.rst, cookbook/mass_edit.rst, cookbook/product_asset/index.rst, reference/workflow/index.rst
I've noticed we have so GREAT video materials, it's time to make them available for developers.
Thinking about Akeneo, I really think every Akeneo developer must have some "product/functional" knowledges about what he is doing, and what is the interest for Julia: what do you think?
=> Introduce product focus videos

conf.py
This extension is deprecated since Sphinx 1.4.
=> Remove deprecated sphinx extension

_themes/akeneo_rtd/static/css/akeneo.css, _themes/sphinx_rtd_theme/footer.html
First test of Website build with platform.sh
=> Added a note in footer

_themes/akeneo_rtd/static/css/akeneo.css, _themes/sphinx_rtd_theme/footer.html
Platform.sh is now enabled on 1.7 branch too :)
=> Added platform.sh note

.travis.yml
This command will be faster to execute and produce more information in case of error 👍 
=> What is a dummy builder?  http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.dummy.DummyBuilder
=> How can you be sure it's more performant?
Looking at our build history, I've noticed an improvement of 15/20% https://travis-ci.org/akeneo/pim-docs/builds
=> Improved script command to run tests

troubleshooting/common_issues/index.rst
add part: I cannot export my products "An exception occurred during the export"
=> Add infos about mem leak on exports

_themes/akeneo_rtd/layout.html, _themes/akeneo_rtd/static/css/akeneo.css, _themes/akeneo_rtd/versions.html, _themes/sphinx_rtd_theme/layout.html
* Display docs version in a better place
* Put consistent margins for versions selector
=> [CherryPick] Display docs version in a better place (#546)

developer_guide/installation/installation_ce_archive.rst
=> Update URLs to PIM archives

reference/import_export/formats/association_type.rst
Add note on association export, behaviour changed in 1.7.
=> Update association page

developer_guide/installation/system_requirements/system_install_debian8.rst, developer_guide/installation/system_requirements/system_install_debian8_php7.rst, developer_guide/installation/system_requirements/system_install_ubuntu_1404.rst, developer_guide/installation/system_requirements/system_install_ubuntu_1604.rst, developer_guide/installation/system_requirements/system_requirements.rst.inc
Remove mcrypt in installation guide after fix issue https://github.com/akeneo/pim-community-dev/pull/6081
=> Remove mcrypt

cookbook/rule/add_custom_action_rule_engine.rst
They are missing steps in the custom action in the rule engine.
If you don't do that, you'll have an error in the rule list page
=> Add code for fixing the rule list page

developer_guide/installation/system_requirements/system_install_ubuntu_1604.rst
* Update system_install_ubuntu_1604.rst
* Update system_install_ubuntu_1604.rst
* Update system_install_ubuntu_1604.rst
* Address comments
=> [Cherry pick] Updated System installation on ubuntu 16.04 (#587)

conf.py
Hello,
it's one of many steps to help us make a better way to deploy the application(https://github.com/akeneo/pim-docs/issues/568).
In our deployment script, I can some `sed` we can remove.
Note this pull request needs to be applied from 1.0 => master.
Mickaël
=> Added dynamic copyright

developer_guide/installation/system_requirements/system_requirements.rst.inc
This contribution needs to be applied from `1.5` to `master` branches.
=> Added Image magick as requirement for EE

styleguide/composer.json, styleguide/index.php
* Styleguide now have his own composer configuration
* fix PHP warning + SEO duplicate content
=> [CherryPick] Standalone styleguide master

install_pim/system_requirements/system_requirements.rst.inc
From
https://github.com/akeneo/pim-docs/issues/565
I add php-exif in system requirement
=>  Add php-exif in system requirements

install_pim/system_requirements/system_configuration.rst.inc
for https://github.com/akeneo/pim-community-dev/pull/6306
=> TIP-425: remove ONLY_FULL_GROUP_BY dirty configuration

cookbook/import_export/product-import-from-xml-file.rst, src/Acme/Bundle/XmlConnectorBundle/Job/JobParameters/SimpleXmlImport.php, src/Acme/Bundle/XmlConnectorBundle/Resources/config/form_extensions/job_instance/xml_product_import_edit.yml, src/Acme/Bundle/XmlConnectorBundle/Resources/config/form_extensions/job_instance/xml_product_import_show.yml, src/Acme/Bundle/XmlConnectorBundle/Resources/config/job_parameters.yml, src/Acme/Bundle/XmlConnectorBundle/Resources/translations/messages.en.yml
- UI form configuration was outdated
- UI configuration files now included in the doc
=> Fix XML Import

.gitignore, .travis.yml, composer.json, composer.lock
See fix from @damien-carcel:
https://github.com/akeneo/pim-docs/pull/633
=> fix Travis Builds for 1.7

developer_guide/installation/partners_portal_archive.rst.inc
Just fixed some typos:
* recieved -> received
* will be send -> will be sent
By the way, fantastic work on this product! Congrats!
=> Typos fixed partners_portal_archive

developer_guide/installation/system_requirements/system_requirements.rst.inc
From : https://github.com/akeneo/pim-docs/issues/383
Add php5-imagick into PHP required module for PIM DOC 1.7
=> Add php5-imagick into PHP required module

contribute_to_pim/documentation.rst, import_and_export_data/formats/attribute.rst, import_and_export_data/formats/examples/attribute_properties.csv, import_and_export_data/product-export.rst, install_pim/installation_docker.rst, manipulate_pim_data/catalog_structure/creating_a_reference_data.rst
This PR cherry-pick this contribution https://github.com/akeneo/pim-docs/pull/622, fixing an error in it (broken link), and solves another broken link described in this issue: https://github.com/akeneo/pim-docs/issues/658.
=> Issue 658: Fix some broken links

design_pim/guides/add_new_page.rst, design_pim/index.rst
Doc about "how to add a new page"
=> [PIM-6887] Add a new page

manipulate_pim_data/catalog_structure/creating_a_reference_data.rst
following my previous PR.. #733
=> Replace "Overriding" by "Configuring" for ProductValue class

_themes/akeneo/layout.html
Fix viandecss layout
Before
After
=> fix-layout: fix layout overflow

_themes/akeneo/layout.html
Same as previous one but for docker pages :)
=> fix inline tt

manipulate_pim_data/rule/general_information_on_rule_format.rst
see https://github.com/akeneo/pim-enterprise-dev/pull/3571
=> PIM-7125: Document "include_children" option in a remove action

Dockerfile, README.md, build.sh
- set `build.sh` independent of version number
- remove `pip`
- make docker image less heavy
=> [deploy] Refactor Dockerfile

install_pim/manual/crontab_tasks.rst.inc, install_pim/manual/crontab_tasks_ee.rst.inc
This fix should be applied for all versions >= 2.0
=> Fixed wrong log paths in crontab commands

manipulate_pim_data/rule/general_information_on_rule_format.rst
Rebased PR https://github.com/akeneo/pim-docs/pull/825
=> Update documentation according new way to query families

cookbook/purge/purge_job_execution.rst
Inform users that this command does not remove archives files (asked many times on github and helpdesk board)
=> Add a comment regarding job executions purge

contributing/report_bug.rst.inc
"Submit your request on our Helpdesk"
=> Update support part for EE

design_pim/guides/how_to_customize_menu.rst
The form_extensions doc was wrong. It corrects it ;)
=> Fix the form_extensions doc

cloud_edition/flexibility_mode/docs/composer_settings.rst, cloud_edition/flexibility_mode/index.rst
backport master docs (cloud parts) to 1.7
=> 1.7 cloud 466

migrate_pim/index.rst
Add info for cloud clients with a link to cloud documentation
=> Update the Migrate PIM Page

import_and_export_data/guides/create-connector.rst
=> Issue 725: Fix broken link on UI customization

install_pim/docker/installation_docker.rst
Related to this proposal: https://github.com/akeneo/pim-community-dev/pull/7895
=> Update documentation about docker-compose

cloud_edition/flexibility_mode/docs/crontasks.rst, cloud_edition/flexibility_mode/docs/pim_application.rst, cloud_edition/flexibility_mode/index.rst
A single page to help partner to manage crontasks and mail notification
=> Cloud-628: Add page for custom cron tasks in flexibility

design_pim/guides/how_to_customize_menu.rst
=> add config director

_themes/akeneo/layout.html, _themes/akeneo/static/css/variables-43bf553955.css
This PR merges the branch "2.3" into "master" and update the "pre-version" notice for a "development" notice.
=> Notice that "master" branch is the development version of the PIM

manipulate_pim_data/catalog_structure/how_to_add_a_custom_unit_of_measure.rst
=> Fix measure.yml file example. Space indentation was wrong

_themes/akeneo/layout.html
Done in pair with @damien-carcel 
=> Uncomment the deprecated message

_themes/akeneo/layout.html, manipulate_pim_data/catalog_structure/how_to_add_a_custom_unit_of_measure.rst
Done in pair with @damien-carcel
=> Comment the deprecated message

install_pim/manual/system_requirements/system_requirements.rst.inc
=> Add mysql server 5.7.22 as a new requirement for the 3.0

technical_architecture/notification/add.rst
This PR fixes & improves documentation on how to add a custom notification factory.
=> FIX & Improve doc about custom notifications

developer_guide/installation/system_requirements/system_requirements.rst.inc
=> PIM-7456: Security vulnerabilities in dependencies

cloud_edition/flexibility_mode/docs/pim_updates_and_migrations.rst, cloud_edition/flexibility_mode/index.rst, cloud_edition/serenity_mode/docs/pim_updates_and_migrations.rst, cloud_edition/serenity_mode/index.rst
Long time ago we were asked to put a bit of doc about PIM upgrad process on Flexibility and Serenity offer.
That's not a lot but at least it cover the need
cf. https://akeneo.atlassian.net/browse/SDS-3067
=> SDS-3067: Document Flexibility & Serenity PIM update/migration process

cloud_edition/flexibility_mode/docs/pim_updates_and_migrations.rst, cloud_edition/flexibility_mode/index.rst, cloud_edition/serenity_mode/docs/pim_updates_and_migrations.rst, cloud_edition/serenity_mode/index.rst
=> Merge 2.0 into 2.1

Dockerfile, cloud_edition/flexibility_mode/docs/pim_updates_and_migrations.rst, cloud_edition/flexibility_mode/index.rst, cloud_edition/serenity_mode/docs/pim_updates_and_migrations.rst, cloud_edition/serenity_mode/index.rst
=> Merge 2.1 into 2.2

cloud_edition/flexibility_mode/docs/pim_updates_and_migrations.rst, cloud_edition/flexibility_mode/index.rst, cloud_edition/serenity_mode/docs/pim_updates_and_migrations.rst, cloud_edition/serenity_mode/index.rst
=> Merge 2.2 into 2.3

maintain_pim/common_issues/index.rst
=> Add missing indexes

install_pim/customize_dataset/index.rst
=> Fixed incorrect  bundle class name

install_pim/manual/installation_ce_archive.rst
Changed repository link for manual ce installation to v2.3
| Check the link is correct        | OK
=> Changed repository link for manual ce installation to v2.3

.github/PULL_REQUEST_TEMPLATE.md, cloud_edition/flexibility_mode/docs/partner_starterkit.rst, install_pim/customize_dataset/index.rst, install_pim/manual/installation_ce_archive.rst, maintain_pim/common_issues/index.rst, manipulate_pim_data/product/update.rst, migrate_pim/index.rst, technical_architecture/best_practices/reusable_bundle.rst, technical_architecture/index.rst, technical_architecture/localization/change_pim_locale.rst
=> Merge 2.3 into master

migrate_pim/index.rst
=> Update infos on how to apply patches or upgrade

manipulate_pim_data/rule/general_information_on_rule_format.rst
=> Update removal action information

cloud_edition/flexibility_mode/docs/partner_starterkit.rst
=> update flexibility  access management on pim-docs 2.3

cloud_edition/flexibility_mode/docs/partner_starterkit.rst
=> CLOUD-772 update flexibility access management 1.7

cloud_edition/flexibility_mode/docs/partner_starterkit.rst
=> CLOUD-772 update flexibility access management 2.0

cloud_edition/flexibility_mode/docs/partner_starterkit.rst
=> CLOUD-772 update flexibility access management 2.1

cloud_edition/flexibility_mode/docs/partner_starterkit.rst
=> CLOUD-772 update flexibility access management 2.2

cloud_edition/flexibility_mode/docs/crontasks.rst, cloud_edition/flexibility_mode/docs/partner_starterkit.rst, cloud_edition/flexibility_mode/docs/pim_application.rst, migrate_pim/index.rst
=> Merge 2.3 master

Dockerfile
Fix a typo that prevents the deployment of the branch `2.2`.
=> Fix 2.2 deployement

maintain_pim/first_aid_kit/index.rst
added --no-warmup in the clear cache command
=> Update cache clear command

_themes/akeneo/layout.html, _themes/akeneo/static/css/variables-43bf553955.css, maintain_pim/first_aid_kit/index.rst
=> Merge 2.3 to Master

Dockerfile
APCU does work with PIM 1.7, we need APC.
=> Deploy doc: fix 1.7 deploy

contribute_to_pim/front.rst, contribute_to_pim/index.rst
=> Add explanation about the build of our frontend

install_pim/docker/installation_docker.rst
The main goal is to update the old reference in technical documentation to use the Portal section of the Help Center for 2.3.
Note: on this PR, the documentation does not reference the Partners Portal but the Portal. Depending if you are a customer or not, you could use the Customer Portal too. This is explained in the Help Center.
PR linked to https://akeneo.atlassian.net/browse/PAPO-1514 on the Portal.
=> Update pim docs 2.3 for the projects console

technical_overview/teamwork_assistant/project_creation.rst
=> Merge 2.1 -> 2.2

technical_overview/teamwork_assistant/project_creation.rst
=> Merge 2.2 -> 2.3

contribute_to_pim/front.rst, contribute_to_pim/index.rst, install_pim/docker/installation_docker.rst, technical_overview/teamwork_assistant/project_creation.rst
=> Merge 2.3 -> master

contribute_to_pim/front.rst
=> Fix commande name in front.rst

cloud_edition/serenity_mode/docs/overview.rst, cloud_edition/serenity_mode/index.rst, install_pim/manual/installation_archive_ee.rst.inc
The main goal is to update the old reference in technical documentation to use the Portal section of the Help Center for 2.0.
On a serenity mode, it adds the documentation on how to set up your instance with the Projects Console in the Portal.
Note: on this PR, the documentation does not reference the Partners Portal but the Portal. Depending if you are a customer or not, you could use the Customer Portal too. This is explained in the Help Center.
PR linked to https://akeneo.atlassian.net/browse/PAPO-1514 on the Portal.
`-`: Not …
=> Update pim docs 2.0 for the projects console

design_pim/guides/how_to_customize_menu.rst
The example was wrong, we have to set the config/to value in order to know the link targeted route.
| Technical Review and 2 GTM        | ok
=> The target route must be set

technical_architecture/technical_information/recommended_configuration.rst, technical_architecture/technical_information/server_side_setup_for_hosting.rst
Seen with @BitOne: it's outdated.
=> Remove hardware configuration

onboarder/installation/index.rst, onboarder/prerequisites/index.rst
=> clarify the use of public and private key

install_pim/docker/installation_docker.rst
=> Add VNC password to see behat tests run

onboarder/installation/index.rst, onboarder/synchronization/index.rst
=> Fix documentation about the onboarder

Dockerfile, install_pim/manual/system_requirements/manual_system_installation_debian9.rst, install_pim/manual/system_requirements/system_install_ubuntu_1604.rst, install_pim/manual/system_requirements/system_requirements.rst.inc
Removes SOAP PHP extension from the dependency list as it's not used.
=> TIP-1018 Removes unused SOAP dependency

install_pim/manual/system_requirements/system_requirements.rst.inc
akeneo/pim-community-dev#9372
akeneo/pim-enterprise-dev#5451
=> Migrate nodeJS 8.x to 10.x

install_pim/customize_dataset/index.rst
This fixes a bad display of a bullets list in the https://docs.akeneo.com/master/install_pim/customize_dataset/index.html documentation page.
=> fix(docs): install_pim/customize_dataset bullet list

use_sso_authentication/index.rst
Those links were created with the master branch target because 3.0 branch didn't exists.
=> Update links that target pim-ee repository from master to 3.0 branch

_themes/akeneo/layout.html
=> Merge 2.3 into 3.0

.github/PULL_REQUEST_TEMPLATE.md, Dockerfile, README.md, cloud_edition/flexibility_mode/docs/composer_settings.rst, contribute_to_pim/contribution_guide.rst, contribute_to_pim/documentation.rst, contribute_to_pim/tests/establishing_decorator_pattern.rst, contribute_to_pim/tests/index.rst, design_pim/guides/create_a_reference_data_crud.rst, import_and_export_data/formats/attribute.rst, import_and_export_data/simple-import.rst, install_pim/docker/installation_docker.rst, install_pim/manual/installation_archive.rst.inc, install_pim/manual/installation_archive_ee.rst.inc, install_pim/manual/installation_ce_archive.rst, manipulate_pim_data/mass_edition/register_a_new_mass_edit_action.rst, manipulate_pim_data/non-product/create.rst, migrate_pim/index.rst, technical_architecture/best_practices/core/behat.rst, technical_architecture/best_practices/core/standards.rst, technical_architecture/best_practices/reusable_bundle.rst, technical_architecture/bundles/akeneo_bundles.rst.inc, technical_architecture/components/akeneo_components.rst.inc, technical_architecture/components/pim_components.rst.inc, technical_architecture/events/storage_events.rst
=> Prepare the doc for the 3.0

onboarder/synchronization/index.rst
Remove details about entities that are no longer synchronized
=> Aob 373 - Remove categories & retailer users synchronization

contribute_to_pim/front.rst, design_pim/guides/add_new_page.rst, design_pim/overview.rst, maintain_pim/common_issues/index.rst, manipulate_pim_data/mass_edition/register_a_new_bulk_action.rst, migrate_pim/index.rst
=> Update frontend docs for the yarn run less command

install_pim/docker/installation_docker.rst
=> fix selenium port in documentation

Dockerfile, docker/wait_for_mysql.sh
Maintain the Dockerfile of the doc.
=> Maintain Dockerfile

onboarder/installation/define_environment_variables/system_environment_variables.rst, onboarder/installation/index.rst, onboarder/prerequisites/index.rst
=> Aob 374 - Product draft are now synchronized directly between Pim master and Supplier onboarder

manipulate_pim_data/rule/general_information_on_rule_format.rst
Update the rule documentation to add the 2 reference entities attributes
=> PIM-8193 Update the rule documentation to add the reference entities attributes

reference_entities/add_custom_property_to_your_custom_attribute_type.rst, reference_entities/create_new_attribute_type.rst, reference_entities/enrich_a_record_with_new_attribute_type.rst, reference_entities/index.rst
=> Add note on the reference entity documentation and fix namespace

cloud_edition/flexibility_mode/docs/crontasks.rst, reference_entities/index.rst, reference_entities/refresh_records.rst
| English Review and 1 GTM          | Ok
=> PIM-8169: Add refresh command documentation

contribute_to_pim/translate.rst
=> More info for Crowdin usage

maintain_pim/first_aid_kit/index.rst
remove the link to the Knowledge base, add links to the Helpcenter and API
Explained catalog volume monitoring page and added a link to the Medium article Because your product catalog typology matters
=> Update the article

Dockerfile, _themes/akeneo_rtd/layout.html, docker/wait_for_mysql.sh
Add deprecated banner & backport Dockerfile
=> Add deprecated banner

_themes/akeneo/layout.html, _themes/akeneo/static/css/variables-43bf553955.css
Merge 1.7 into 2.0 and add deprecated banner for 2.0
=> Merge 1.7 into 2.0 and add deprecate banner for 2.0

contribute_to_pim/translate.rst
=> Fix errors

Dockerfile
The Dockerfile is not working
`docker build --tag pim-docs:master .`  error out `Sub-process /usr/bin/dpkg returned an error code (1)`
`apt-get upgrade` should probably not be executed.
=> Fix Dockerfile error on apt upgrade

install_pim/manual/system_requirements/system_requirements.rst.inc, technical_architecture/best_practices/reusable_bundle.rst
Add a warning to the system requirements section regarding mysql and cloud managed mysql services.
=> Add warning regarding cloud mysql managed service.

migrate_pim/upgrade_minor_version.rst, technical_architecture/best_practices/reusable_bundle.rst, technical_overview/teamwork_assistant/behat_permission_summary.rst
=> Prepare 3.1 release

Dockerfile, technical_architecture/best_practices/reusable_bundle.rst
=> Fix Dockerfile

Dockerfile, technical_architecture/best_practices/reusable_bundle.rst
=> Fix dockerfile 2.1

Dockerfile
Fixes the Dockerfile in order to correctly generate the assets used by styleguide pages as of 3.1 version
=> Styleguide deployment 3.1

Dockerfile, install_pim/manual/installation_ce_archive.rst, migrate_pim/upgrade_minor_version.rst, technical_architecture/best_practices/reusable_bundle.rst, technical_overview/teamwork_assistant/behat_permission_summary.rst, use_sso_authentication/index.rst
=> Merge 3.1 into master

install_pim/manual/daemon_queue.rst
Here a contribution linked to this feature: https://github.com/akeneo/pim-community-dev/pull/9988
=> DAPI-245: Update job queue documentation with specific consumer example

onboarder/installation/index.rst
=> Add command to create ES index for pre ref products

install_pim/customize_dataset/index.rst, install_pim/manual/installation_archive.rst.inc
cf. https://github.com/akeneo/pim-community-dev/pull/10075
=> Remove admin from minimal catalog

use_sso_authentication/index.rst
=> TIP-1093: Update SAML log path

_themes/akeneo/_versions.html, _themes/akeneo/static/js/versions.js, conf.py
Backport https://github.com/akeneo/pim-docs/pull/1194
=> Fetch versions in AJAX way

install_pim/manual/daemon_queue.rst
=> PIM-8384: Update job queue documentation with specific consumer example

import_and_export_data/guides/automate-import-exports.rst
| Technical Review and 2 GTM        | 
| English Review and 1 GTM          | 
=> fix render --username

reference_entities/create_new_attribute_type.rst, reference_entities/enrich_a_record_with_new_attribute_type.rst
=> Documentation about adding an attribute type for the API of the reference entity feature

onboarder/installation/index.rst
=> Change the version of the onboarder

design_pim/overview.rst
Fixed typo in Summary section.
=> Fixed typo in Summary

technical_architecture/technical_information/client_side_compatibilities.rst
=> Fix firefox versions compatibilities

contribute_to_pim/contribution_guide.rst, contribute_to_pim/create_connector.rst, contribute_to_pim/documentation.rst, contribute_to_pim/feature_request.rst.inc, contribute_to_pim/tests/establishing_decorator_pattern.rst, contribute_to_pim/tests/index.rst, manipulate_pim_data/mass_edition/register_a_new_mass_edit_action.rst, migrate_pim/apply_patch/apply_patch_ee_flexibility.rst, technical_architecture/best_practices/core/behat.rst
=> Update grammar in apply_patch_ee_flexibility.rst

_themes/akeneo/layout.html
=> Release 3.2: remove 'master' warning

_themes/akeneo/layout.html
=> Release 3.2: deprecate 3.1

install_pim/customize_dataset/index.rst
=> Update 'How to customize the Dataset' doc

manipulate_pim_data/rule/add_custom_action_rule_engine.rst
=> Fix docs for the rule engine

install_pim/manual/installation_archive.rst.inc
=> Update version from 3.1 to 3.2

install_pim/manual/installation_archive.rst.inc
Clarified that you have to create a admin user in order to login into the pim
=> clarify you need to create a admin user

cloud_edition/flexibility_mode/docs/partners.rst
=> Cloud 1121 31

cloud_edition/flexibility_mode/docs/partners.rst
=> Fix commands for partners

cloud_edition/flexibility_mode/docs/disk_usage.rst, cloud_edition/flexibility_mode/index.rst
=> CLOUD-1213: Add doc about flex disk usage

manipulate_pim_data/product/query.rst
=> Fix namespace markdown rendering

manipulate_pim_data/non-product/create.rst
=> Fix typos on factory classname 

install_pim/manual/installation_archive_ee.rst.inc, manipulate_pim_data/rule/add_custom_action_rule_engine.rst
-> Fix datagrid for rules.
-> add user command for ee install
=> Improve doc

use_sso_authentication/index.rst
=> PIM-8665 Change SSO logs location to DB

use_sso_authentication/index.rst
This PR fixes the docker-compose port number that was conflicting with Behat.
=> PIM-8665 Fixes wrong default port for SAML IdP docker

manipulate_pim_data/rule/add_custom_action_rule_engine.rst
=> Merge 3.0 into master

onboarder/installation/index.rst, onboarder/prerequisites/index.rst
This PR updates the Onboarder documentation for the PIM 3.2.
=> AOB-589: Udpate PIM Onboarder version bundle

cloud_edition/flexibility_mode/docs/partners.rst
**For PIM 3.x versions (3.0, 3.1, 3.2)**
CLOUD-1274
=> CLOUD-1274 Enable new daemons with systemctl (for PIM 3.x)

technical_architecture/events/storage_events.rst
Updates links and FQCN for enrichment subscribers
=> Update enrichment subscribers paths

install_pim/docker/installation_docker.rst
=> Fix typo in docker installation

cloud_edition/flexibility_mode/docs/partners.rst
=> Fix typo partners.rst

cloud_edition/flexibility_mode/docs/onboarder.rst, cloud_edition/flexibility_mode/index.rst, onboarder/synchronization/index.rst
Add a Flex specific documentation for enabling the Onboarder worker.
=> AOB-729: How to launch Onboarder worker on Flex

cloud_edition/flexibility_mode/docs/onboarder.rst, cloud_edition/flexibility_mode/index.rst, onboarder/synchronization/index.rst
=> Merge 3.0 into 3.1

cloud_edition/flexibility_mode/docs/onboarder.rst, cloud_edition/flexibility_mode/docs/partners.rst, cloud_edition/flexibility_mode/index.rst, onboarder/synchronization/index.rst, technical_architecture/events/storage_events.rst
=> Merge 3.1 into 3.2

install_pim/docker/installation_docker.rst
=> Fix typo on command to create user

src/Acme/Bundle/XmlConnectorBundle/Resources/config/job_parameters.yml
From version 3.0 there is no '%pim_enrich.provider.form.job_instance.class% parameter
=> Fix for a nonexistent parameter

contribute_to_pim/documentation.rst, onboarder/installation/index.rst
=> Update documentation for 2.3.0 onboarder tag

onboarder/index.rst, onboarder/migrate/apply_patch/apply_patch_ee_flexibility.rst, onboarder/migrate/apply_patch/apply_patch_ee_on_premise.rst, onboarder/migrate/apply_patch/index.rst, onboarder/migrate/index.rst, onboarder/migrate/upgrade_major_version.rst, onboarder/migrate/upgrade_minor_version.rst
=> AOB-699: Add Onboarder migration doc

cloud_edition/flexibility_mode/docs/crontasks.rst, contribute_to_pim/contribution_guide.rst, contribute_to_pim/documentation.rst, technical_architecture/localization/how_to_use_the_presenters.rst, technical_architecture/standard_format/index.rst, use_sso_authentication/index.rst
Adds information on the command to purge SSO log entries.
=> PIM 8665 purge command

cloud_edition/flexibility_mode/docs/crontasks.rst, install_pim/manual/crontab_tasks.rst.inc, install_pim/manual/crontab_tasks_ee.rst.inc
I kept the wrong use of `--env=prod` for now, as it should be fixed in another PR in my opinion (the whole documentation should be updated for SF4).
=> Remove cron about calculation of the completeness

cloud_edition/flexibility_mode/docs/onboarder.rst
Update the documentation according to the new `systemd` management.
=> CLOUD-1466: Manage PIM Onboarder workers on Flex

.gitignore, Dockerfile, Makefile, README.md, build.sh
=> TIP-1361: Deploy pim-docs with makefile commands

install_pim/manual/system_requirements/system_requirements.rst.inc
=> TIP-1277: upgrade mysql to the last version

design_pim/guides/add_a_custom_button_to_product_edit_form.rst, design_pim/guides/add_a_tab_to_form.rst, import_and_export_data/guides/create-connector.rst, src/Acme/Bundle/NotifyConnectorBundle/Resources/config/form_extensions/csv_product_export_notify_edit.yml, src/Acme/Bundle/NotifyConnectorBundle/Resources/config/form_extensions/csv_product_export_notify_show.yml
Doc was not up to date.
I re-did it from scratch, now it works
https://akeneo.atlassian.net/browse/PIM-9038
=> PIM-9038: Fix connector doc

README.md
=> Fix typo in the links to list the workflows in circle CI

Makefile
We need to build the documentation before deploying it.
=> Fix deployment on Circle CI

cloud_edition/flexibility_mode/docs/crontasks.rst, install_pim/manual/crontab_tasks.rst.inc, install_pim/manual/crontab_tasks_ee.rst.inc
=> Adds refresh audit data in crontasks list

install_pim/docker/installation_docker.rst
Adds option to Docker installation in order to work properly with our distribution server.
=> Fixes installation from PAPO

migrate_pim/upgrade_from_32_to_40.rst
Common migration doc between CE and EE.
=> Uses same doc for CE and EE

cloud_edition/flexibility_mode/docs/crontasks.rst, install_pim/manual/crontab_tasks_ee.rst.inc
=> update cron list

.circleci/config.yml, README.md
=> Activate the continuous deployment of the 4.0 branch

.platform.app.yaml, Dockerfile, install_pim/manual/common_install_ce_ee.rst.inc, install_pim/manual/installation_ce.rst, install_pim/manual/installation_ee_archive.rst, technical_architecture/technical_information/application_technical_dependencies.rst
=> Fix the documentation to install Akeneo PIM in 4.0

install_pim/docker/installation_docker.rst
=> Fix broken link

.platform.app.yaml, Dockerfile, _themes/akeneo/layout.html, conf.py, install_pim/docker/installation_docker.rst, install_pim/manual/common_install_ce_ee.rst.inc, install_pim/manual/installation_ce.rst, install_pim/manual/installation_ee_archive.rst, technical_architecture/technical_information/application_technical_dependencies.rst
=> Merge 4.0 into master

migrate_pim/upgrade/upgrade_from_32_to_40.rst
=> Add information about the new value factories chamges

install_pim/docker/installation_docker.rst
=> Fix docker run documentation command

cloud_edition/flexibility_mode/docs/crontasks.rst
=> API-844: Add crontab about purge read product

conf.py, maintain_pim/common_issues/index.rst
I removed the difference between CE and EE because this is now the same code.
=> PIM-9136: Fix elasticsearch custom configuration example

manipulate_pim_data/rule/general_information_on_rule_format.rst
Add the support of the simple and multi select label translations.  
If the translation cannot be found, we use the code of the option. 
=> RUL-44: add support of the simple and multi select label translations

manipulate_pim_data/rule/general_information_on_rule_format.rst
Add and describe the new *concatenate* action in rule engine
=> RUL-47: add concatenate action rule

cloud_edition/flexibility_mode/docs/disk_usage.rst, contribute_to_pim/contribution_guide.rst, contribute_to_pim/tests/establishing_decorator_pattern.rst, contribute_to_pim/tests/index.rst, import_and_export_data/simple-import.rst, install_pim/manual/system_requirements/manual_system_installation_debian10.rst, install_pim/manual/system_requirements/system_install_ubuntu_1804.rst, manipulate_pim_data/mass_edition/register_a_new_mass_edit_action.rst, manipulate_pim_data/non-product/create.rst, technical_architecture/best_practices/core/behat.rst, technical_architecture/best_practices/core/standards.rst, technical_architecture/best_practices/reusable_bundle.rst, technical_architecture/events/storage_events.rst, technical_architecture/events/workflow_events.rst, technical_architecture/index.rst
Replaces links with the their proper versions so the target matches the current PIM version.
=> Uses proper versions in links

install_pim/manual/system_requirements/system_requirements.rst.inc
=> DAPI-895: update documentation to add Norvegian and Portuguese languages support for spellchecking

manipulate_pim_data/index.rst, manipulate_pim_data/store_assets_externally.rst
This PR adds instructions on how to store assets externally.
=> Adds external storage for assets instructions

.circleci/config.yml, Makefile
Fixes CircleCI to allow deployement
=> Fixes deployement

.circleci/config.yml
=> Fixes Circle CI config

.circleci/config.yml
=> Fixes Circle CI permission problem

.circleci/config.yml
Fixes Circle CI prod deployment rights
=> Fixes Circle CI prod deployement

manipulate_pim_data/rule/add_custom_action_rule_engine.rst
=> PIM-9166: Fix "How to add a custom action in the rule engine"

maintain_pim/common_issues/index.rst
Update documentation relative to this PR : https://github.com/akeneo/pim-community-dev/pull/11838
=> PIM-9163: total_fields limit of elasticsearch should be configurable

manipulate_pim_data/rule/general_information_on_rule_format.rst
Updates the rules page for ADD and SET associations actions.
=> RUL-106: Update rules documentation for SET/ADD associations

manipulate_pim_data/rule/general_information_on_rule_format.rst
Add CLEAR action documentation.
The english review is done by Camille on the same PR on helpcenter (https://github.com/akeneo/pim-helpcenter/pull/530).
=> RUL-97: add clear action documentation

manipulate_pim_data/store_assets_externally.rst
Following SDS-13264 latest does not work. Removed from the documentation.
Added links to AWS SDK Documentation
=> Changed code block and added AWS documentation

.github/PULL_REQUEST_TEMPLATE.md
Update the PR template for external contribution
=> External contributions must be done on the default branch

install_pim/docker/installation_docker.rst
Changed pim-xx and pim-xx-cli into pim-docker-cli et pim-docker-web
=> Updated message about Server names

manipulate_pim_data/index.rst, manipulate_pim_data/measurement/configure_measurement_limits.rst
=> MET-94: Adds docs about measurement limits

manipulate_pim_data/rule/general_information_on_rule_format.rst
=> Fix rule labels format

manipulate_pim_data/rule/general_information_on_rule_format.rst
=> RUL-28: Add calculate action

onboarder/installation/index.rst, onboarder/prerequisites/index.rst
The Onboarder bundle 4.0 was just released. This PR updates the documentation explaining how to install the bundle on a PIM 4.0.
=> AOB-880: Update Onboarder install docs for 4.0

onboarder/installation/index.rst, onboarder/migrate/apply_patch/apply_patch_ee_flexibility.rst, onboarder/migrate/apply_patch/apply_patch_ee_on_premise.rst
=> Put the good bundle version

cloud_edition/flexibility_mode/docs/onboarder.rst, cloud_edition/serenity_mode/docs/pim_updates_and_migrations.rst, design_pim/guides/add_a_custom_button_to_product_edit_form.rst, design_pim/guides/add_a_tab_to_form.rst, import_and_export_data/guides/create-connector.rst, maintain_pim/purge/purge_job_execution.rst, manipulate_pim_data/catalog_structure/how_to_add_a_custom_unit_of_measure.rst, migrate_pim/upgrade_major_version.rst, onboarder/index.rst, onboarder/migrate/apply_patch/apply_patch_ee_flexibility.rst, onboarder/migrate/apply_patch/apply_patch_ee_on_premise.rst, onboarder/migrate/apply_patch/index.rst, onboarder/migrate/index.rst, onboarder/migrate/upgrade_major_version.rst, onboarder/migrate/upgrade_minor_version.rst, src/Acme/Bundle/NotifyConnectorBundle/Resources/config/form_extensions/csv_product_export_notify_edit.yml, src/Acme/Bundle/NotifyConnectorBundle/Resources/config/form_extensions/csv_product_export_notify_show.yml, src/Acme/Bundle/XmlConnectorBundle/Resources/config/job_parameters.yml
| English Review and 1 GTM          | OK
=> Pull 3.2 -> 4.0

onboarder/installation/index.rst, onboarder/prerequisites/index.rst, onboarder/synchronization/index.rst
This PR replaces retailer onboarder occurences by middleware. Retailer onboarder is the old name we used to use for the middleware.
It also fix an error for the max supported version of the PIM.
=> Onboarder doc improvements

.circleci/config.yml, Makefile, scripts/test_php_uses.sh
Fixes docker UID and GID when deploying
=> Fixes docker call

onboarder/installation/index.rst
This PR adds a front building step to the onboarder installation documentation.
=> Add front building step to onboarder installation doc

onboarder/installation/index.rst
=> Onboarder installation improvements

manipulate_pim_data/rule/general_information_on_rule_format.rst
Add a section for the `round_precision` parameter
=> RUL-242: calculate round

onboarder/installation/define_environment_variables/dot_env_component.rst, onboarder/installation/index.rst
A client had some difficulties setting up the Onboarder extension into their PIM. It revealed a few mistakes and lack of clarity that this PR tries to address.
=> SDS-14079: Fix Onboarder installation issues

manipulate_pim_data/rule/general_information_on_rule_format.rst
=> RUL-271: relative date format for rules

manipulate_pim_data/rule/general_information_on_rule_format.rst
Add new operators, set the old ones deprecated
=> RUL-346 completeness operators

cloud_edition/flexibility_mode/docs/crontasks.rst
=> DAPI-1196 - remove franklin from documentation in 3.1

cloud_edition/flexibility_mode/docs/crontasks.rst, install_pim/manual/crontab_tasks_ee.rst.inc
=> Dapi 1196 - remove franklin from documentation in 3.2

onboarder/installation/index.rst
See https://github.com/akeneo/pim-onboarder/pull/572
=> AOB-1016: Add instruction to clear the cache after bundle activation

manipulate_pim_data/rule/general_information_on_rule_format.rst
=> Fix available operator list in rule engine

manipulate_pim_data/rule/general_information_on_rule_format.rst
Add 2 options in the concatenate action rule:
- `text` to add a specific text
- `new_line` to add a new line / line break
=> RUL-448: add text and new_line options in concatenate action rule

manipulate_pim_data/rule/add_custom_action_rule_engine.rst, manipulate_pim_data/rule/general_information_on_rule_format.rst
=> RUL-91: add enabled key info on rule import

onboarder/installation/index.rst
Documentation update following Onboarder bundle 3.3.0 release.
=> Update onboarder install documentation following 3.3.0 release

onboarder/installation/index.rst
Documentation update following Onboarder bundle 4.2.0 release.
=> Update onboarder install documentation following 4.2.0 release

manipulate_pim_data/measurement/configure_measurement_limits.rst
=> RAC-311: Update measurement family limits

cloud_edition/flexibility_mode/docs/disk_usage.rst
New sandbox and production instances will have the same disk capacity from now.
I took the opportunity to make a pass on the document and fixed some typos.
=> CLOUD-2177: Normalize sandbox/production instances

Dockerfile, manipulate_pim_data/rule/general_information_on_rule_format.rst
Also fix the build using composer v2  
=> CPM-74: add unit_label_locale in concatenate action rule

cloud_edition/flexibility_mode/docs/disk_usage.rst
Add instructions for the following operations on Flexibility:
- check disk usage
- check disk usage distribution
=> CLOUD-2179: Describe how to monitor disk space usage on Flexibility

import_and_export_data/guides/create-connector.rst
=> RAC-406: Make a job stoppable

manipulate_pim_data/rule/general_information_on_rule_format.rst
=> RUL-465: Document conditions on family_variant, entity_type and parent fields

migrate_pim/upgrade/upgrade_from_40_to_50.rst
=> DAPI-1240 - add data quality insights migration specificities

install_pim/customize_dataset/index.rst, install_pim/docker/installation_docker.rst, install_pim/manual/system_requirements/system_requirements.rst.inc, migrate_pim/apply_patch/apply_patch_ee_flexibility.rst, migrate_pim/apply_patch/apply_patch_ee_on_premise.rst
=> BH-80: Fix some links format and update some version number to be up to date.

migrate_pim/upgrade/upgrade_from_40_to_50.rst
=> BH-231 Rename upgrade upgrade-front

README.md
=> Bh 240 - Initial deploy of 5.0 on staging.

.circleci/config.yml
=> correct circle ci for 5.0 deploy

.circleci/config.yml
=> Bh 240 fix ci

onboarder/installation/index.rst
| English Review and 1 GTM          |  -
=> AOB-1235: Fix typo in onboarder install documentation

migrate_pim/upgrade/upgrade_from_40_to_50.rst
=> BH-275 correct rector installation command

.circleci/config.yml
=> Automatize the pull up in master from 5.0 branch

onboarder/installation/index.rst, onboarder/prerequisites/index.rst
A new `FLAG_ONBOARDER_ENABLED` environment variable was introduce along the feature flag bundle. This PR documents its usage for our users.
=> AOB-1272: Document the Onboarder feature activation

Makefile, onboarder/installation/index.rst, scripts/update-doc-versions.php
=> BH-299: manage version index on pim-docs

.circleci/config.yml
=> BH-321 Add pull-up to and nightly build (to check links)

Makefile
=> BH-381 Fixes staging deployment

.circleci/config.yml
=> ci: Fix typo to trigger pull-up workflow

.circleci/config.yml, onboarder/installation/index.rst, src/Acme/Bundle/CatalogBundle/Form/Type/CategoryType.php, src/Acme/Bundle/CatalogBundle/Form/Type/TranslatableCategoryType.php, src/Acme/Bundle/CatalogBundle/Resources/config/form_types.yml
=> Merge 40 50

install_pim/manual/daemon_queue.rst
Fix some mistakes, and reword the sentences with our beloved english teacher
=> Improve sentence

.circleci/config.yml
Pullup mechanism is only useful to master, not *from* master. So this PR removes this pull up configuration from master.
=> Remove useless pullup tools on master

.circleci/config.yml
This issue was introduced in a big pullup: https://github.com/akeneo/pim-docs/commit/6fcbe4a5e30d25b2de4a2103776fa4ac90197905#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L18
=> Fix CI deployment for master branch

install_pim/manual/system_requirements/manual_system_installation_debian10.rst, install_pim/manual/system_requirements/system_requirements.rst.inc
=> BH-416: Changed php-memcached to a non-generic package

install_pim/manual/system_requirements/manual_system_installation_debian10.rst, install_pim/manual/system_requirements/system_install_ubuntu_1804.rst, install_pim/manual/system_requirements/system_requirements.rst.inc
=> BH-426: Choose a fixed MySQL Version

install_pim/docker/installation_docker.rst, install_pim/manual/system_requirements/manual_system_installation_debian10.rst, install_pim/manual/system_requirements/system_install_ubuntu_1804.rst, install_pim/manual/system_requirements/system_requirements.rst.inc
xdebug configuration fixes & small simplification.
=> BH-432 Installation fixes for v5

install_pim/docker/installation_docker.rst, install_pim/manual/system_requirements/manual_system_installation_debian10.rst, install_pim/manual/system_requirements/system_install_ubuntu_1804.rst, install_pim/manual/system_requirements/system_requirements.rst.inc
=> 50 to master benoit

conf.py
=> restore master version due to bad base branch

migrate_pim/upgrade/upgrade_from_40_to_50.rst
=> PIM-9753: Add the prepare 4 to 5 command for CE

Dockerfile, Makefile, index.rst, reference_entities/index.rst, scripts/test_php_uses.sh, technical_architecture/best_practices/core/behat.rst, troubleshooting/index.rst
Add a "Troubleshooting guide" section and add the first item for PIM-9750
=> PIM-9750: Add "Troubleshooting guide" section

install_pim/manual/system_requirements/system_requirements.rst.inc
=> #1600: Precision for servers open ports

cloud_edition/flexibility_mode/index.rst, migrate_pim/apply_patch/apply_patch_ee_flexibility.rst
- Rewrite the APC cache commands for Flexibility product
- Add a auto-complete link for technological upgrade request on Jira
=> Rewrite APC cache docs

conf.py
=> BH-422 restore master version due to bad base branch

import_and_export_data/formats/examples/attribute_properties.csv, technical_architecture/standard_format/other_entities.rst
=> CPM-141: Add the guidelines property for attribute

cloud_edition/flexibility_mode/docs/crontasks.rst
Backported here https://github.com/akeneo/pim-docs/pull/1620
=> Update crontab doc

cloud_edition/flexibility_mode/docs/disk_usage.rst
=> RAC-590: update the documentation to purge asset orphans

manipulate_pim_data/connect/configure_event_subscription_network.rst, manipulate_pim_data/index.rst
=> API-1602: Add doc on how to configure Event Subscription IP whitelist

migrate_pim/upgrade/upgrade_from_40_to_50.rst
=> PIM-9917 document DQI migration command

onboarder/installation/index.rst
- [AOB-1365](https://akeneo.atlassian.net/browse/AOB-1365) Update front-end command install
- [AOB-1398](https://akeneo.atlassian.net/browse/AOB-1398) Add documentation concerning the environment variables necessary for the proper functioning of the onboarder 
=> AOB-1365 AOB-1398 Onboarder 5.0

onboarder/installation/index.rst
- [AOB-1365](https://akeneo.atlassian.net/browse/AOB-1365) Update front-end command install
- [AOB-1398](https://akeneo.atlassian.net/browse/AOB-1398) Add documentation concerning the environment variables necessary for the proper functioning of the onboarder 
=> AOB-1365 - AOB-1398 - Onboarder 4.0

install_pim/docker/installation_docker.rst, install_pim/manual/daemon_queue.rst
In the nest release the way to run job daemons will change
=> CPM-152: update job consuming

cloud_edition/flexibility_mode/docs/environments_access.rst, conf.py, onboarder/index.rst, onboarder/uninstall/index.rst
Document how to deactivate the Onboarder bundle:
- Create uninstall folder and index file with related instructions
=> [OB-903] Document how to deactivate the Onboarder bundle

cloud_edition/flexibility_mode/docs/environments_access.rst, cloud_edition/flexibility_mode/docs/job_consumers_and_workers.rst, conf.py
=> Remove journalctl command 5.0

cloud_edition/flexibility_mode/docs/environments_access.rst, cloud_edition/flexibility_mode/docs/job_consumers_and_workers.rst, conf.py
=> Remove journalctl command 4.0

cloud_edition/flexibility_mode/docs/job_consumers_and_workers.rst
=> Remove journalctl command master

cloud_edition/flexibility_mode/docs/environments_access.rst, cloud_edition/flexibility_mode/index.rst
=> Improve Helpdesk links

cloud_edition/flexibility_mode/docs/disk_usage.rst
Following a change made in this PR: https://github.com/akeneo/pim-enterprise-dev/pull/11690
=> RAC-868: Update thumbnail clear command usage with --all

reference_entities/configure_entity_limits.rst
Update documentation according to increased limit
| Technical Review and 2 GTM        | Done
=> RAC-853: Update documentation according to increased limit

onboarder/prerequisites/index.rst
Fix PIM version Onboarder compatibility
=> Fix PIM version Onboarder compatibility

onboarder/installation/index.rst
With the 4.0 EOL, we released a new major for the onboarder bundle: `^5.0`. This commit change the current carret version from 4.2 to 5.0.
=> Update onboarder installation process

migrate_pim/apply_patch/apply_patch_ee_flexibility.rst
=> Fix How to apply patch regarding package.json

Dockerfile
=> Fix deployment regression

.circleci/config.yml, Makefile, scripts/test_php_uses_composer.json
Fixes prod deployment by setting the `no-api` flag which avoid API rate limit errors.
=> PIM-10188: Fixes prod deployment

index.rst, logshell_flexv4.rst, logshell_saas_flexv5.rst
Add pages for Log4Shell communication
=> LOG4SHELL Add pages to go from in-app comm

logshell_flexv4.rst, logshell_flexv5.rst
Adds additional information for onprem users.
=> LOG4SHELL Adds info for on-premise customers

logshell_saas.rst
Fixes Typo on log4shell vulnerability communication.
=> LOG4SHELL Typo fix

logshell_flexv4.rst, logshell_flexv5.rst, logshell_saas.rst
Upgrade the pages following the application of the mitigation.
=> LOG4SHELL Post upgrade on Flex v4 and below

.circleci/config.yml, Dockerfile, cloud_edition/flexibility_mode/docs/environments_access.rst, conf.py, contribute_to_pim/tests/establishing_decorator_pattern.rst, import_and_export_data/guides/create-connector.rst, install_pim/docker/installation_docker.rst, install_pim/manual/common_install_ce_ee.rst.inc, manipulate_pim_data/teamwork_assistant/activate_loggable_step.rst, manipulate_pim_data/teamwork_assistant/add_project_remover.rst, reference_entities/add_custom_property_to_your_custom_attribute_type.rst, reference_entities/create_new_attribute_type.rst, reference_entities/enrich_a_record_with_new_attribute_type.rst, technical_architecture/best_practices/reusable_bundle.rst, technical_architecture/localization/how_to_use_the_localizers.rst, technical_overview/teamwork_assistant/behat_permission_summary.rst, technical_overview/teamwork_assistant/project_completeness.rst, technical_overview/teamwork_assistant/project_creation.rst, technical_overview/teamwork_assistant/scalability_guide.rst, technical_overview/teamwork_assistant/widget_extension_points.rst
Using a more recent version of Sphinx allows us to fix an issue with the User Agent in the linkchecker.
It also discovered some broken links and syntax errors (use of html instead of rst)
To do so, I changed the Dockerfile to install a python3 compatible Sphinx, as python2 is limited to Sphinx 1.x
=> Fix documentation

onboarder/prerequisites/index.rst
Update prerequisites for Onboarder, 6.0 not supported yet.
=> Update prerequisites for Onboarder (6.0 not supported yet)

onboarder/installation/index.rst
Add a link to Synchronization page at the end of Onboarder installation page. Customers / partners needs to follow all those steps to have a working Onboarder.
=> Improve Onboarder installation documentation

contribute_to_pim/create_connector.rst
=> Marketplace renaming

onboarder/prerequisites/index.rst
Update Onboarder prerequisites with PIM 6.0 support.
=> Update Onboarder prerequisites with PIM 6.0 support

migrate_pim/upgrade/upgrade_from_50_to_60.rst
=> Update upgrade file - add warning

onboarder/installation/index.rst, onboarder/synchronization/index.rst, onboarder/troubleshooting/index.rst
Upgrade onboarder installation documentation and troubleshooting page since we have renamed the env var for Google PubSub.
=> AOB-1455: Upgrade onboarder installation and troubleshooting doc

migrate_pim/upgrade/upgrade_from_50_to_60.rst
=> PIM-10344: [Backport] Add dqi command to launch in 5.0 to 6.0 migration

migrate_pim/upgrade/upgrade_from_60_to_70.rst, migrate_pim/upgrade_major_version.rst
The goal is to ensure that the command `bin/console pim:data-quality-insights:populate-product-models-scores-and-ki` will be executed after the migrations.
=> PLG-779: initiate doc to migrate from 6.0 to 7.0

import_and_export_data/index.rst, install_pim/manual/installation_ce.rst, install_pim/manual/installation_ee_archive.rst, install_pim/manual/system_requirements/manual_system_installation_debian10.rst, install_pim/manual/system_requirements/system_install_ubuntu_1804.rst, install_pim/manual/system_requirements/system_install_ubuntu_2004.rst, install_pim/manual/system_requirements/system_requirements.rst.inc, migrate_pim/apply_patch/apply_patch_ce.rst, migrate_pim/apply_patch/apply_patch_ee_flexibility.rst, migrate_pim/apply_patch/apply_patch_ee_on_premise.rst, technical_architecture/technical_information/application_technical_dependencies.rst, technical_architecture/technical_information/php_ini.rst.inc
=> Pim 10376 + PIM-10375: Updates for 6.0 version

contribute_to_pim/contribution_guide.rst, contribute_to_pim/documentation.rst, contribute_to_pim/report_bug.rst.inc, contribute_to_pim/translate.rst
=> Remove links to badger

migrate_pim/upgrade/upgrade_from_60_to_70.rst
Add dqi command to launch before doctrine migrations link to this PR: https://github.com/akeneo/pim-community-dev/pull/16743
=> PLG-469: Add dqi command to launch before doctrine migrations

onboarder/installation/index.rst, onboarder/prerequisites/index.rst
Update Onboarder instructions for PIM 6.x.
=> OB-1185: Update Onboarder compatibility for PIM 6.x

.circleci/config.yml, technical_architecture/events/storage_events.rst
Fixes two outdated external links
=> Hotfix: Fix external links issues

migrate_pim/apply_patch/apply_patch_ee_flexibility.rst
https://docs.akeneo.com/5.0/migrate_pim/apply_patch/apply_patch_ee_flexibility.html
=> FIx typo of patch version to apply

use_sso_authentication/index.rst
=> Add email to possible akeneo_uid values

contribute_to_pim/create_connector.rst
=> MW-369 - update app store url from marketplace to apps

cve_2022_46157.rst
=> fix: patch link

migrate_pim/upgrade/upgrade_from_40_to_50.rst
=> Fix upgrade documentation for migrations

onboarder/installation/index.rst, onboarder/prerequisites/index.rst
Update Onboarder instructions for PIM 7.x.
=> OB-1315 : Update Onboarder compatibility for PIM 7.x

migrate_pim/index.rst
=> SQUIR-114 - upgrade index migrate pim

_themes/akeneo/layout.html, migrate_pim/upgrade/upgrade_from_60_to_70.rst
=> Release official flexv7

cloud_edition/flexibility_mode/docs/composer_settings.rst, maintain_pim/first_aid_kit/index.rst
=> Fix broken link since helpjuice

migrate_pim/apply_patch/apply_patch_ce.rst
=> [SQUIR-118] Improve How to apply a patch -  Community

migrate_pim/apply_patch/apply_patch_ee_on_premise.rst
=> [SQUIR-122] Improve How to apply a patch - On-prem

migrate_pim/apply_patch/apply_patch_ee_flexibility.rst
=> SQUIR-120 Update apply_patch_ee_flexibility.rst

migrate_pim/changelog.rst
=> SQUIR-124 - Upgrade "where is the changelog" page

migrate_pim/upgrade_minor_version.rst
=> SQUIR-126 - Upgrade how to upgrade to minor version

cloud_edition/flexibility_mode/docs/system_administration.rst
=> SQUIR-141 - Rewrite system administration page

cloud_edition/flexibility_mode/index.rst
page: https://docs.akeneo.com/6.0/cloud_edition/flexibility_mode/index.html
=> [SQUIR-137] Improve Flexibility main page

cloud_edition/flexibility_mode/docs/job_consumers_and_workers.rst, maintain_pim/first_aid_kit/index.rst, onboarder/synchronization/index.rst
This PR moves Onboarder bundle related section to the synchronization section of the Onboarder documentation
=> AOB-1584 Move systemd Onboarder worker documentation to the Onboarder synchronization section

cloud_edition/flexibility_mode/docs/job_consumers_and_workers.rst, maintain_pim/first_aid_kit/index.rst, onboarder/synchronization/index.rst
This PR moves Onboarder bundle related section to the synchronization section of the Onboarder documentation
=> AOB-1584 Move systemd Onboarder worker documentation to the Onboarder synchronization section (7.0)

index.rst, migrate_pim/index.rst, migrate_pim/migrate_to_saas.rst
* Adds a page that describes the process of upgrading a Flexibility or On Premise EE instance to Serenity
* Walks users through the basic steps needed to generate the information Support needs to begin the upgrade process
This will be added to the `Guides` drop-down menu and linked from the `Upgrade Akeneo PIM projects` page (we cannot directly put it in both trees because of the way that our docs site works).
The new page itself will contain the information that is usually provided by CS, PS, or Support, as well as rudimentary troubleshooting and a short list of things to expect.
=> [SQUIR-157] docs.akeneo.com page for Flex to Srnt migration

onboarder/installation/index.rst
Integrating process to fix broken installation after onboarder setup
=> 📝 Update of onboarder installation documentation

import_and_export_data/guides/create-connector.rst, import_and_export_data/simple-import.rst, src/Acme/Bundle/NotifyConnectorBundle/Resources/config/form_extensions/csv_product_export_notify_edit.yml, src/Acme/Bundle/NotifyConnectorBundle/Resources/config/form_extensions/csv_product_export_notify_show.yml, src/Acme/Bundle/NotifyConnectorBundle/Step/NotifyStep.php, src/Acme/Bundle/XmlConnectorBundle/Archiver/XmlInvalidItemWriter.php, src/Acme/Bundle/XmlConnectorBundle/Job/JobParameters/SimpleXmlImport.php, src/Acme/Bundle/XmlConnectorBundle/Reader/File/XmlProductReader.php, src/Acme/Bundle/XmlConnectorBundle/Resources/config/form_extensions/job_instance/xml_product_import_edit.yml, src/Acme/Bundle/XmlConnectorBundle/Resources/config/form_extensions/job_instance/xml_product_import_show.yml, src/Acme/Bundle/XmlConnectorBundle/Writer/XmlWriter.php, use_sso_authentication/index.rst
In this PR, I fixed the technical documentation in order to take into account that now we have storage since 7.0
=> PIM-11193: Fix wrong documentation about file path since storage have been introduce

import_and_export_data/guides/create-connector.rst, import_and_export_data/simple-import.rst, install_pim/manual/index.rst, install_pim/manual/security_recommendations.rst, onboarder/installation/index.rst, src/Acme/Bundle/NotifyConnectorBundle/Resources/config/form_extensions/csv_product_export_notify_edit.yml, src/Acme/Bundle/NotifyConnectorBundle/Resources/config/form_extensions/csv_product_export_notify_show.yml, src/Acme/Bundle/NotifyConnectorBundle/Step/NotifyStep.php, src/Acme/Bundle/XmlConnectorBundle/Archiver/XmlInvalidItemWriter.php, src/Acme/Bundle/XmlConnectorBundle/Job/JobParameters/SimpleXmlImport.php, src/Acme/Bundle/XmlConnectorBundle/Reader/File/XmlProductReader.php, src/Acme/Bundle/XmlConnectorBundle/Resources/config/form_extensions/job_instance/xml_product_import_edit.yml, src/Acme/Bundle/XmlConnectorBundle/Resources/config/form_extensions/job_instance/xml_product_import_show.yml, src/Acme/Bundle/XmlConnectorBundle/Writer/XmlWriter.php, use_sso_authentication/index.rst
=> PIM-11193: Pullup 7.0 to master

index.rst, maintain_pim/first_aid_kit/index.rst, migrate_pim/migrate_to_saas.rst
This updates and pulls up the SaaS to PaaS migration documentation (initially created for v6).
=> Pull up SaaS upgrade instructions to 7.0 docs

migrate_pim/apply_patch/apply_patch_ee_flexibility.rst
=> Upgrade commands

onboarder/uninstall/index.rst
In this PR we add command to clean data onboarder
=> OB-update-docs: Update doc to clean onboarder

conf.py, index.rst, maintain_pim/first_aid_kit/index.rst, migrate_pim/migrate_to_saas.rst
Editing files for adding to this PR : 
- index.rst
- maintain_pim/first_aid_kit/index.rst
- migrate_pim/migrate_to_saas.rst
=> Backport pr1871 into v7.0

conf.py, migrate_pim/upgrade/upgrade_from_60_to_70.rst
As clients might have a cache issue after building the front for a stack upgrade from v6 to v7, I added the commands the clients can run to clear the cache if this issue arises.
=> [SQUIR-224] Add cache clear command after building front

migrate_pim/migrate_to_saas.rst
[SQUIR-233] Following first PR https://github.com/akeneo/pim-docs/pull/1880 to add information on the doc to remove symlinks and check file structure, editing the markdown for a better visibility
[SQUIR-233]: https://akeneo.atlassian.net/browse/SQUIR-233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SQUIR-233] following PR 1880, editing markdown

Dockerfile, cloud_edition/flexibility_mode/docs/composer_settings.rst, cloud_edition/flexibility_mode/docs/job_consumers_and_workers.rst, conf.py, install_pim/docker/installation_docker.rst, install_pim/manual/installation_ee_archive.rst, migrate_pim/apply_patch/apply_patch_ee_flexibility.rst, migrate_pim/apply_patch/apply_patch_ee_on_premise.rst, migrate_pim/changelog.rst, migrate_pim/upgrade/upgrade_from_32_to_40.rst, migrate_pim/upgrade/upgrade_from_40_to_50.rst, migrate_pim/upgrade/upgrade_from_50_to_60.rst, migrate_pim/upgrade_major_version.rst, migrate_pim/upgrade_minor_version.rst
Edited last paragraph mentionning disabling webhook consumer which is not possible.
Instead, added explanations on how to start, restart or check the webhook consumer status
=> SQUIR-236 Remove paragraph about disabling webhook & replace it by by start and status checking

Dockerfile, cloud_edition/flexibility_mode/docs/composer_settings.rst, cloud_edition/flexibility_mode/docs/job_consumers_and_workers.rst, install_pim/docker/installation_docker.rst, install_pim/manual/installation_ee_archive.rst, migrate_pim/changelog.rst, migrate_pim/upgrade/upgrade_from_32_to_40.rst, migrate_pim/upgrade/upgrade_from_40_to_50.rst, migrate_pim/upgrade/upgrade_from_50_to_60.rst, migrate_pim/upgrade/upgrade_from_60_to_70.rst, migrate_pim/upgrade_major_version.rst
Edited last paragraph mentionning disabling webhook consumer which is not possible.
Instead, added explanations on how to start, restart or check the webhook consumer status
=> SQUIR-236-7.0 Remove paragraph about disabling webhook & replace it by start and status checking

Dockerfile, cloud_edition/flexibility_mode/docs/composer_settings.rst, cloud_edition/flexibility_mode/docs/job_consumers_and_workers.rst, conf.py, contribute_to_pim/report_bug.rst.inc, install_pim/docker/installation_docker.rst, install_pim/manual/installation_ee_archive.rst, migrate_pim/changelog.rst, migrate_pim/upgrade/upgrade_from_32_to_40.rst, migrate_pim/upgrade/upgrade_from_40_to_50.rst, migrate_pim/upgrade/upgrade_from_50_to_60.rst, migrate_pim/upgrade/upgrade_from_60_to_70.rst, migrate_pim/upgrade_major_version.rst
Edited last paragraph mentionning disabling webhook consumer which is not possible.
Instead, added explanations on how to start, restart or check the webhook consumer status
=> SQUIR-236-master Remove paragraph about disabling webhook & replace it by start and status checking

contribute_to_pim/contribution_guide.rst, import_and_export_data/formats/attribute.rst, maintain_pim/scalability_guide/more_than_10k_attributes.rst
| English Review and 1 GTM          | Pauline K
=> CHPSUPPORT-167: Add more information about performance benchmarks for PIM

maintain_pim/scalability_guide/more_than_10k_attributes.rst
Update intro for more_than_10k_attributes in V7
=> Update intro for more_than_10k_attributes
